-- Deprecated bootstrap entry point.
--
-- The original prototype schema exposed anonymous mutations for live commuter counts.
-- Phase 1 no longer publishes or accepts those counts. Do not apply this file.
-- Use versioned migrations in supabase/migrations and seed data in supabase/seed.sql:
--
--   supabase db reset   -- local development
--   supabase db push    -- linked project after review
