import Link from 'next/link'

export const metadata = {
  title: 'About Slugging | Sluglines',
    description: 'Learn about slugging, the unique form of casual carpooling in Northern Virginia that has been connecting commuters since 1975.',
    }

    export default function AboutSluggingPage() {
      return (
          <div className="max-w-4xl mx-auto px-4 py-12">
                <div className="mb-10">
                        <h1 className="text-4xl font-extrabold text-slate-900 mb-4">About Slugging</h1>
                                <p className="text-lg text-slate-600 leading-relaxed">
                                          Commuters strive to find the most efficient transportation to save time, stress and money. The Washington DC metro area commuters are no different — they came up with a solution to avoid traffic congestion and leverage the High Occupancy Vehicles (HOV) lanes.
                                                  </p>
                                                        </div>

                                                              <div className="prose prose-slate max-w-none space-y-8">
                                                                      <section className="bg-white rounded-2xl border border-slate-200 p-6 md:p-8">
                                                                                <h2 className="text-2xl font-bold text-slate-900 mb-4">What is Slugging?</h2>
                                                                                          <p className="text-slate-600 leading-relaxed">
                                                                                                      "Slugging" — aka "casual carpool" — is a unique method of transportation used by about 10,000 commuters along the I-95 corridor. Slugging is dynamic ride sharing where drivers and riders commuting in the same direction match up and ride together to comply with HOV restrictions. The best part is that slugging is free for the riders, and drivers get to drive on HOV lanes and avoid paying tolls!
                                                                                                                </p>
                                                                                                                        </section>
                                                                                                                        
                                                                                                                                <section className="bg-white rounded-2xl border border-slate-200 p-6 md:p-8">
                                                                                                                                          <h2 className="text-2xl font-bold text-slate-900 mb-4">Where Does the Term "Slugging" Come From?</h2>
                                                                                                                                                    <p className="text-slate-600 leading-relaxed">
                                                                                                                                                                Slugs were referred to as fake or counterfeit bus tokens that people would try to pass as real fare — something bus drivers kept a watchful eye out for. Commuter bus drivers adopted the same name for riders who were waiting at a bus stop hoping for a free ride. It eventually evolved to refer to this unique type of commuting called "slug line."
                                                                                                                                                                          </p>
                                                                                                                                                                                  </section>
                                                                                                                                                                                  
                                                                                                                                                                                          <section className="bg-white rounded-2xl border border-slate-200 p-6 md:p-8">
                                                                                                                                                                                                    <h2 className="text-2xl font-bold text-slate-900 mb-4">A 40-Year History</h2>
                                                                                                                                                                                                              <p className="text-slate-600 leading-relaxed mb-4">
                                                                                                                                                                                                                          Slugging has been a part of DC commuting methods for around 40 years — starting in 1975, shortly after the creation of the first HOV lanes on I-395, also known as "The Shirley Highway." These lanes were part of many changes that came about due to the 1970s Arab oil embargo, which caused gas prices to soar, speed limits to be reduced, cars to become more fuel efficient, and HOV lanes to be created. All of this was done in an effort to reduce gasoline consumption, but it also had a major positive impact on the environment.
                                                                                                                                                                                                                                    </p>
                                                                                                                                                                                                                                              <p className="text-slate-600 leading-relaxed mb-4">
                                                                                                                                                                                                                                                          HOV lanes were made to encourage people to carpool, and the rules were strictly enforced even then. But because these lanes made commuting so much easier, drivers began stopping at bus stops and offering rides to anyone waiting. This gave people a new option that was much faster and more reliable than the bus — and free.
                                                                                                                                                                                                                                                                    </p>
                                                                                                                                                                                                                                                                              <p className="text-slate-600 leading-relaxed">
                                                                                                                                                                                                                                                                                          Since then, HOT (High-Occupancy Toll) lanes — open to high-occupancy vehicles — have also been created along I-66, I-395, and I-95. As a result, slug lines have become even more sought after as a means of getting an easier commute. Now, slug lines operate along both I-95 and I-66 corridors in the Northern Virginia and DC areas, with drivers offering free rides to people who would otherwise spend considerable time waiting on public transportation.
                                                                                                                                                                                                                                                                                                    </p>
                                                                                                                                                                                                                                                                                                            </section>
                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                    <section className="bg-blue-50 rounded-2xl border border-blue-100 p-6 md:p-8">
                                                                                                                                                                                                                                                                                                                              <h2 className="text-2xl font-bold text-slate-900 mb-4">Why Try Slugging?</h2>
                                                                                                                                                                                                                                                                                                                                        <ul className="space-y-3 text-slate-600">
                                                                                                                                                                                                                                                                                                                                                    <li className="flex items-start gap-3">
                                                                                                                                                                                                                                                                                                                                                                  <span className="w-2 h-2 rounded-full bg-blue-500 mt-2 shrink-0"></span>
                                                                                                                                                                                                                                                                                                                                                                                <span>It is <strong>fast</strong> — access to express HOV/HOT lanes can cut 30–45 minutes off your commute.</span>
                                                                                                                                                                                                                                                                                                                                                                                            </li>
                                                                                                                                                                                                                                                                                                                                                                                                        <li className="flex items-start gap-3">
                                                                                                                                                                                                                                                                                                                                                                                                                      <span className="w-2 h-2 rounded-full bg-blue-500 mt-2 shrink-0"></span>
                                                                                                                                                                                                                                                                                                                                                                                                                                    <span>It is <strong>free</strong> — no money is ever exchanged between drivers and riders.</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                </li>
                                                                                                                                                                                                                                                                                                                                                                                                                                                            <li className="flex items-start gap-3">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <span className="w-2 h-2 rounded-full bg-blue-500 mt-2 shrink-0"></span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <span>It is <strong>safe</strong> — slug lines have operated safely for decades with an excellent track record.</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </li>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <li className="flex items-start gap-3">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <span className="w-2 h-2 rounded-full bg-blue-500 mt-2 shrink-0"></span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <span>It is <strong>community-driven</strong> — a time-honored tradition maintained by the commuters themselves.</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </li>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <li className="flex items-start gap-3">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <span className="w-2 h-2 rounded-full bg-blue-500 mt-2 shrink-0"></span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <span>It is <strong>eco-friendly</strong> — fewer cars on the road means reduced emissions and less congestion.</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </li>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </ul>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div className="mt-6 flex flex-wrap gap-4">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <Link href="/spots" className="btn-primary">Find a Slug Line Spot</Link>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <Link href="/how-it-works" className="btn-secondary">How It Works</Link>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </section>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }
