import Link from 'next/link'
import { Mail, Facebook, Twitter, Youtube } from 'lucide-react'

export const metadata = {
  title: 'About Us | Sluglines',
    description: 'Learn about Sluglines — a site for commuters, by commuters, dedicated to connecting drivers and riders for better commutes in Northern Virginia.',
    }

    export default function AboutUsPage() {
      return (
          <div className="max-w-4xl mx-auto px-4 py-12">
                <div className="mb-10">
                        <h1 className="text-4xl font-extrabold text-slate-900 mb-4">About Us</h1>
                                <p className="text-lg text-slate-600 leading-relaxed">
                                          Welcome to Sluglines, a site committed to connecting commuters like you. We embrace an alternative type of transportation called slugging — a casual form of carpooling that not only gets passengers a free ride, but gives drivers access to HOV and HOT lanes.
                                                  </p>
                                                        </div>

                                                              <div className="space-y-8">
                                                                      <section className="bg-white rounded-2xl border border-slate-200 p-6 md:p-8">
                                                                                <h2 className="text-2xl font-bold text-slate-900 mb-4">What Makes Sluglines Unique</h2>
                                                                                          <p className="text-slate-600 leading-relaxed mb-4">
                                                                                                      Sluglines is unique because we help improve communication between commuters through our searchable map database, forums, and integration with social media. Social networks like Facebook, Twitter, and YouTube share slug line status from the commuters themselves.
                                                                                                                </p>
                                                                                                                          <p className="text-slate-600 leading-relaxed">
                                                                                                                                      Based in Washington D.C., Sluglines gets its name from the long line of commuters waiting at designated slugging locations. We are here to make those lines run smoother and a whole lot faster by bringing community to the slugging world.
                                                                                                                                                </p>
                                                                                                                                                        </section>
                                                                                                                                                        
                                                                                                                                                                <section className="bg-white rounded-2xl border border-slate-200 p-6 md:p-8">
                                                                                                                                                                          <h2 className="text-2xl font-bold text-slate-900 mb-4">Our Story</h2>
                                                                                                                                                                                    <p className="text-slate-600 leading-relaxed mb-4">
                                                                                                                                                                                                After nearly a decade of commuting, we were fed up with rising gas prices, tolls, and the slower-than-ever pace of traffic. "There must be something better than this," we thought. As it turns out, there was — something that connects drivers and riders for an altogether more efficient commute. It's called slugging.
                                                                                                                                                                                                          </p>
                                                                                                                                                                                                                    <p className="text-slate-600 leading-relaxed">
                                                                                                                                                                                                                                The only problem was, we couldn't find a single online tool where drivers and riders could connect beforehand to reduce wait times. That is when we created Sluglines — a site for commuters, by commuters. Whether you are a frustrated driver or a passenger in search of an easier commute, our site was designed to offer you a better way to navigate the slug lines.
                                                                                                                                                                                                                                          </p>
                                                                                                                                                                                                                                                  </section>
                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                          <section className="bg-white rounded-2xl border border-slate-200 p-6 md:p-8">
                                                                                                                                                                                                                                                                    <h2 className="text-2xl font-bold text-slate-900 mb-4">Lost & Found</h2>
                                                                                                                                                                                                                                                                              <p className="text-slate-600 leading-relaxed">
                                                                                                                                                                                                                                                                                          Lost or found items while slugging to or from work? Post it on the{' '}
                                                                                                                                                                                                                                                                                                      <Link href="/forum" className="text-blue-600 hover:underline">Sluglines Lost and Found forum</Link>{' '}
                                                                                                                                                                                                                                                                                                                  or on the Sluglines Facebook page for a quick response. We welcome your ideas to improve commute — email us or post on social media.
                                                                                                                                                                                                                                                                                                                            </p>
                                                                                                                                                                                                                                                                                                                                    </section>
                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                            <section className="bg-blue-50 rounded-2xl border border-blue-100 p-6 md:p-8">
                                                                                                                                                                                                                                                                                                                                                      <h2 className="text-2xl font-bold text-slate-900 mb-4">Contact & Social Media</h2>
                                                                                                                                                                                                                                                                                                                                                                <div className="space-y-4">
                                                                                                                                                                                                                                                                                                                                                                            <div className="flex items-center gap-3">
                                                                                                                                                                                                                                                                                                                                                                                          <Mail className="w-5 h-5 text-blue-600 shrink-0" />
                                                                                                                                                                                                                                                                                                                                                                                                        <div>
                                                                                                                                                                                                                                                                                                                                                                                                                        <div className="font-medium text-slate-900">Email</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                        <a href="mailto:admin@sluglines.com" className="text-blue-600 hover:underline text-sm">admin@sluglines.com</a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div className="flex items-center gap-3">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <Facebook className="w-5 h-5 text-blue-600 shrink-0" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div className="font-medium text-slate-900">Facebook</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <a href="https://facebook.com/sluglines" target="_blank" rel="noopener noreferrer" className="text-blue-600 hover:underline text-sm">facebook.com/sluglines</a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div className="flex items-center gap-3">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <Twitter className="w-5 h-5 text-blue-600 shrink-0" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div className="font-medium text-slate-900">Twitter / X</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <a href="https://twitter.com/sluglines" target="_blank" rel="noopener noreferrer" className="text-blue-600 hover:underline text-sm">twitter.com/sluglines</a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div className="flex items-center gap-3">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <Youtube className="w-5 h-5 text-blue-600 shrink-0" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div className="font-medium text-slate-900">YouTube</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <a href="https://www.youtube.com/sluglines" target="_blank" rel="noopener noreferrer" className="text-blue-600 hover:underline text-sm">youtube.com/sluglines</a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div className="mt-6">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <p className="text-sm text-slate-600">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      Got shorter wait times? We do. Share your ideas and help us improve the community!
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </section>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
