/**
 * `lib/domain/locations.ts` — the spot location directory (rev. 5.3 §11 P1).
 *
 * This module is the **single source of truth** for the spot inventory. Three
 * things are generated from or checked against it, and none of them owns a copy:
 *
 *   - `supabase/migrations/0004_spot_locations_directory.sql` — generated by
 *     `scripts/seed-locations.mjs`, which `tests/spot-locations-directory.test.mjs`
 *     re-runs and compares byte-for-byte against the committed file. The SQL and
 *     this array therefore cannot drift apart without a red test.
 *   - `src/lib/spot-directory.ts` — the presentation adapter. It maps this array
 *     into the `DirectorySpot` shape the existing components consume; it no
 *     longer holds spot data.
 *   - the legacy `/slug_pickup/**` inventory in `src/data/legacy-site-content.json`,
 *     every spot slug of which must appear below (same test).
 *
 * BOUNDARY (rev. 5.3 §8, enforced by `tests/domain-boundaries.test.mjs`)
 * ---------------------------------------------------------------------------
 * `lib/domain/**` imports `lib/supabase` only — never React, never `lib/ai`. So
 * the inventory lives here as committed data rather than being read from the
 * legacy JSON at runtime: the domain layer does not reach outward, and a
 * directory that a rendering module could edit is not a directory.
 *
 * SLUGS: `slug` vs. `routeSlug`
 * ---------------------------------------------------------------------------
 * `slug` is the canonical lower-case key. It is what the database stores, what
 * the legacy `/slug_pickup/<slug>/` URLs used, and what every lookup normalises
 * to. `routeSlug` preserves the historical casing this app already serves at
 * `/spots/<routeSlug>` (e.g. `Horner-Rd`). They differ only in case, but the
 * distinction is load-bearing: collapsing them would change live URLs, and
 * collapsing them the other way would make the database key case-sensitive.
 *
 * COORDINATES ARE NULLABLE, DELIBERATELY
 * ---------------------------------------------------------------------------
 * Four spots carry `latitude: null, longitude: null` — the four that exist only
 * in the legacy inventory. Their legacy pages publish no coordinates, and this
 * repo does not invent data. `null` is the honest value; a plausible-looking
 * guess would be indistinguishable from a surveyed one. See `Docs/DECISIONS.md`
 * D-31.
 */

export type SpotCorridor = 'I-395 / I-95' | 'I-66'
export type SpotDirection = 'Morning' | 'Afternoon'

/**
 * A spot's media asset, self-hosted. **A transit diagram, not a photograph.**
 *
 * NOT a database column, deliberately. `0004_spot_locations_directory.sql` is
 * generated from this file by `scripts/seed-locations.mjs` and guarded
 * byte-for-byte, so a field that entered `SEED_COLUMNS` would regenerate it.
 * Nothing queries by image and no RLS decision attaches to a static asset path,
 * so this lives in the domain module and `0004` applies untouched (issue #18).
 *
 * `src` is always a path under `public/`. Never a remote URL: a hotlink to
 * sluglines.com dies the day WordPress is cancelled, which is the point of the
 * migration.
 *
 * WHAT THESE FILES ARE, AND WHAT THEY ARE NOT
 * ---------------------------------------------------------------------------
 * `Docs/asset-register.md` classifies all 27 legacy assets: 12 Google Maps
 * aerials, 8 third-party transit or parking schematics, 6 dated route-change
 * notices, 1 promotional flyer, and **zero photographs of a location**. D-39
 * declined to migrate any of them. D-58 migrates **only the 8 schematics** —
 * drawn agency lot diagrams with bus-bay listings, space counts and legends —
 * and holds the other 19 out: the Google aerials carry Google's own credit and
 * its terms, the notices are 2018-2019 and would render as current, and the
 * flyer is a marketing graphic with a contact address on it.
 *
 * So this field is a **transit diagram**, never a photograph. A diagram of a lot
 * is useful orientation; the same file captioned as a photograph would claim a
 * currency and an authorship it does not have — the same failure as a guessed
 * coordinate (D-31) or a fabricated count (D-33). #26 still tracks sourcing real
 * photographs, and this field is not it.
 */
export interface SpotImage {
  /** Path under `public/`, e.g. `/spots/horner-rd.jpg`. Never a remote URL. */
  src: string
  /** Intrinsic pixel size, so `next/image` reserves the box and CLS stays at 0. */
  width: number
  height: number
  /** Describes the spot for a screen reader, not the file. */
  alt: string
  /** Provenance: the legacy URL this file came from. Asserted against LEGACY_IMAGE_PREFIX. */
  sourceUrl: string
  /** ISO date the file was pulled from the legacy site. */
  fetchedAt: string
}

export interface SpotLocation {
  /** Canonical lower-case key: the database key and the legacy URL slug. */
  slug: string
  /** Case-preserved path segment this app serves today. */
  routeSlug: string
  name: string
  corridor: SpotCorridor
  direction: SpotDirection
  county: string
  destination: string
  description: string
  /** `null` where no surveyed coordinate exists. Never guessed. */
  latitude: number | null
  longitude: number | null
  /** Whether a line is believed to be running. Inactive spots stay in the directory. */
  active: boolean
  /**
   * Where this record's operational facts came from and how current they are
   * (issue #36). Required, not optional: an unstated provenance is precisely the
   * problem this models — it renders as confidence the record has not earned.
   */
  provenance: SpotProvenance
  peakHours?: string
  parking?: string
  linesFrom?: string[]
  linesTo?: string[]
  fbUrl?: string
  notes?: string
  /** Absent where the legacy page published no diagram. Never a stand-in. */
  image?: SpotImage
}

/**
 * Publication state for a spot's operational facts — `peakHours`, `parking`,
 * `linesFrom`/`linesTo`, `description` (issue #36).
 *
 * Salvaged from `codex/phase-1`'s `Docs/content-sources.md` during the #11
 * triage. The problem it solves is the one this repo already takes seriously
 * everywhere else: a commuter reading "peak hours 5:30–9:00" cannot tell whether
 * that was confirmed last month or scraped from a 2018 post, because the app
 * renders both with identical authority. Null coordinates are never guessed
 * (D-31) and counts render `unavailable` rather than a fabricated zero (D-33);
 * directory facts were the remaining surface with no honesty mechanism.
 *
 *   verified            Confirmed against a current primary source, or a dated
 *                       on-site review by an editor.
 *   community-reported  Recently reported, not yet corroborated by a primary
 *                       source.
 *   needs-review        Useful orientation whose current operation has not been
 *                       confirmed. The honest state for anything inherited.
 *   historical          Retained for context, never presented as current
 *                       instructions.
 *
 * SOURCE HIERARCHY, strongest first: government or transit-operator pages; then
 * current on-site signage confirmed by an editor; then corroborated community
 * reports; then legacy Sluglines material, which is background and discovery
 * only and never on its own sufficient for `verified`.
 */
export type SpotFactState = 'verified' | 'community-reported' | 'needs-review' | 'historical'

export interface SpotProvenance {
  state: SpotFactState
  /** Where the operational facts came from. Free text, but name a real source. */
  source: string
  /**
   * ISO date the facts were last checked against that source — the date of the
   * *check*, not of the import. Absent where no check has ever happened, which is
   * different from a check that found nothing and must not be back-filled with an
   * import date to make the record look attended to.
   */
  checkedAt?: string
}

/**
 * The states whose facts must not be presented as current instructions without a
 * qualifier. `verified` is deliberately absent: a verified fact needs no badge,
 * which is what keeps the badge meaningful rather than decorative.
 */
export function needsFreshnessQualifier(spot: Pick<SpotLocation, 'provenance'>): boolean {
  return spot.provenance.state !== 'verified'
}

/**
 * The only path a migrated image may have come from (issue #18).
 *
 * Deliberately the narrow `slugging_locations/` path and not `images/`. Three
 * spots publish their asset one directory up, and all three are Google Maps
 * aerials that D-58 declined to migrate; widening the prefix to admit them would
 * remove the guard at the moment it was doing its job. Some legacy pages also
 * embed an `lh5.googleusercontent.com` commenter avatar, which is a person, not
 * a spot.
 */
export const LEGACY_IMAGE_PREFIX = 'https://sluglines.com/images/slugging_locations/'

export function spotImage(slug: string): SpotImage | undefined {
  return findSpotLocation(slug)?.image
}

export const SPOT_CORRIDORS: readonly SpotCorridor[] = ['I-395 / I-95', 'I-66']
export const SPOT_DIRECTIONS: readonly SpotDirection[] = ['Morning', 'Afternoon']

/**
 * The directory, ordered corridor → direction → county so the file reads the way
 * the site groups it. Order is not semantic: every consumer groups or filters.
 */
export const SPOT_LOCATIONS: readonly SpotLocation[] = [
  {
    slug: 'bobs-old-keene-mill-rd',
    routeSlug: 'Bobs-Old-Keene-Mill-Rd',
    name: 'Bob\'s - Old Keene Mill Rd',
    corridor: 'I-395 / I-95',
    direction: 'Morning',
    county: 'Fairfax',
    destination: 'Pentagon, L\'Enfant Plaza, and downtown DC',
    description: 'One of the oldest and best-known Springfield slug lines. Morning riders use Bob\'s / Old Keene Mill for common Pentagon and downtown DC destinations.',
    latitude: 38.7783912,
    longitude: -77.1873566,
    active: true,
    provenance: {
      state: 'needs-review',
      source: 'sluglines.com WordPress export (legacy site; its own content predates 2020)',
    },
    peakHours: '5:45 AM - 8:00 AM',
    parking: 'Large commuter parking area around Springfield Plaza and nearby lots.',
    linesFrom: ['L\'Enfant Plaza', '14th Street', '18th Street', 'Pentagon'],
    linesTo: ['L\'Enfant Plaza', '14th Street', '18th Street', 'Pentagon'],
    fbUrl: 'https://www.facebook.com/groups/springfieldsluglines/',
    image: {
      src: '/spots/Bobs.jpg',
      width: 460,
      height: 344,
      alt: 'Transit diagram for Bob\'s - Old Keene Mill Rd, republished from the legacy sluglines.com page for this spot.',
      sourceUrl: 'https://sluglines.com/images/slugging_locations/Bobs.jpg',
      fetchedAt: '2026-08-22',
    },
  },
  {
    slug: 'cardinal-forest-plaza',
    routeSlug: 'cardinal-forest-plaza',
    name: 'Cardinal Forest Plaza',
    corridor: 'I-395 / I-95',
    direction: 'Morning',
    county: 'Fairfax',
    destination: 'Pentagon, L\'Enfant Plaza, and 14th Street',
    description: 'Cardinal Forest Plaza is a morning slug line location in Fairfax serving the I-395 / I-95 corridor.',
    latitude: 38.7794583,
    longitude: -77.2314818,
    active: true,
    provenance: {
      state: 'needs-review',
      source: 'sluglines.com WordPress export (legacy site; its own content predates 2020)',
    },
    peakHours: '6:00 AM - 8:30 AM',
    linesFrom: ['L\'Enfant Plaza', 'Pentagon', '14th Street'],
  },
  {
    slug: 'franconia-springfield',
    routeSlug: 'Franconia-Springfield',
    name: 'Franconia - Springfield',
    corridor: 'I-395 / I-95',
    direction: 'Morning',
    county: 'Fairfax',
    destination: 'Pentagon, downtown DC, and Northern Virginia commuter destinations',
    description: 'Franconia - Springfield is a morning slug line location in Fairfax serving the I-395 / I-95 corridor.',
    latitude: 38.767306,
    longitude: -77.168972,
    active: false,
    provenance: {
      state: 'needs-review',
      source: 'sluglines.com WordPress export (legacy site; its own content predates 2020)',
    },
  },
  {
    slug: 'lorton',
    routeSlug: 'Lorton',
    name: 'Lorton',
    corridor: 'I-395 / I-95',
    direction: 'Morning',
    county: 'Fairfax',
    destination: 'Pentagon, downtown DC, and Northern Virginia commuter destinations',
    description: 'Lorton is a morning slug line location in Fairfax serving the I-395 / I-95 corridor.',
    latitude: 38.715012,
    longitude: -77.213593,
    active: false,
    provenance: {
      state: 'needs-review',
      source: 'sluglines.com WordPress export (legacy site; its own content predates 2020)',
    },
    image: {
      src: '/spots/Lorton.jpg',
      width: 460,
      height: 302,
      alt: 'Transit diagram for Lorton, republished from the legacy sluglines.com page for this spot.',
      sourceUrl: 'https://sluglines.com/images/slugging_locations/Lorton.jpg',
      fetchedAt: '2026-08-22',
    },
  },
  {
    slug: 'rolling-valley',
    routeSlug: 'Rolling-Valley',
    name: 'Rolling Valley',
    corridor: 'I-395 / I-95',
    direction: 'Morning',
    county: 'Fairfax',
    destination: 'Pentagon, L\'Enfant Plaza, and 14th Street',
    description: 'Rolling Valley is a morning slug line location in Fairfax serving the I-395 / I-95 corridor.',
    latitude: 38.7758648,
    longitude: -77.2629826,
    active: true,
    provenance: {
      state: 'needs-review',
      source: 'sluglines.com WordPress export (legacy site; its own content predates 2020)',
    },
    peakHours: '6:00 AM - 8:30 AM',
    linesFrom: ['Pentagon', 'L\'Enfant Plaza', '14th Street'],
    image: {
      src: '/spots/Rolling_Valley.jpg',
      width: 460,
      height: 341,
      alt: 'Transit diagram for Rolling Valley, republished from the legacy sluglines.com page for this spot.',
      sourceUrl: 'https://sluglines.com/images/slugging_locations/Rolling_Valley.jpg',
      fetchedAt: '2026-08-22',
    },
  },
  {
    slug: 'saratoga',
    routeSlug: 'Saratoga',
    name: 'Saratoga',
    corridor: 'I-395 / I-95',
    direction: 'Morning',
    county: 'Fairfax',
    destination: 'Pentagon, downtown DC, and Northern Virginia commuter destinations',
    description: 'Saratoga is a morning slug line location in Fairfax serving the I-395 / I-95 corridor.',
    latitude: 38.7454983,
    longitude: -77.2100791,
    active: false,
    provenance: {
      state: 'needs-review',
      source: 'sluglines.com WordPress export (legacy site; its own content predates 2020)',
    },
    image: {
      src: '/spots/Saratoga.jpg',
      width: 460,
      height: 355,
      alt: 'Transit diagram for Saratoga, republished from the legacy sluglines.com page for this spot.',
      sourceUrl: 'https://sluglines.com/images/slugging_locations/Saratoga.jpg',
      fetchedAt: '2026-08-22',
    },
  },
  {
    slug: 'sydenstricker-rd',
    routeSlug: 'Sydenstricker-Rd',
    name: 'Sydenstricker Rd',
    corridor: 'I-395 / I-95',
    direction: 'Morning',
    county: 'Fairfax',
    destination: 'Pentagon, L\'Enfant Plaza, and 14th Street',
    description: 'Sydenstricker Rd is a morning slug line location in Fairfax serving the I-395 / I-95 corridor.',
    latitude: 38.755989,
    longitude: -77.238098,
    active: true,
    provenance: {
      state: 'needs-review',
      source: 'sluglines.com WordPress export (legacy site; its own content predates 2020)',
    },
    peakHours: '6:00 AM - 8:30 AM',
    image: {
      src: '/spots/Sydenstricker.jpg',
      width: 460,
      height: 309,
      alt: 'Transit diagram for Sydenstricker Rd, republished from the legacy sluglines.com page for this spot.',
      sourceUrl: 'https://sluglines.com/images/slugging_locations/Sydenstricker.jpg',
      fetchedAt: '2026-08-22',
    },
  },
  {
    slug: 'springfield-town-center',
    routeSlug: 'springfield-town-center',
    name: 'Springfield Town Center',
    corridor: 'I-395 / I-95',
    direction: 'Morning',
    county: 'Fairfax',
    destination: 'L\'Enfant Plaza, 14th at Commerce Dept., and 18th Street',
    description: 'Frontier Garage commuter parking leased by Fairfax County. The legacy page records "there are no sluglines at this time" — commuters park here and walk to Franconia-Springfield Metro.',
    latitude: null,
    longitude: null,
    active: false,
    provenance: {
      state: 'needs-review',
      source: 'sluglines.com WordPress export (legacy site; its own content predates 2020)',
    },
    parking: '800 commuter spaces at the Frontier Garage on levels 2, 4 and 6.',
    linesFrom: ['L\'Enfant Plaza', '14th at Commerce Dept.', '18th Street'],
    linesTo: ['L\'Enfant Plaza', '14th at Commerce Dept.', '14th & Madison Dr', '19th & F Street'],
    fbUrl: 'https://www.facebook.com/groups/STCSluglines/',
    notes: 'Legacy-only: present in the /slug_pickup/ inventory, absent from the curated live directory. No coordinates on the legacy page.',
  },
  {
    slug: 'van-dorn-st',
    routeSlug: 'van-dorn-st',
    name: 'Van Dorn St',
    corridor: 'I-395 / I-95',
    direction: 'Morning',
    county: 'Fairfax / Alexandria',
    destination: 'L\'Enfant Plaza, 14th Street, and 18th Street',
    description: 'Van Dorn Metro park-and-ride. The legacy page title carries an explicit [Inactive] marker.',
    latitude: null,
    longitude: null,
    active: false,
    provenance: {
      state: 'needs-review',
      source: 'sluglines.com WordPress export (legacy site; its own content predates 2020)',
    },
    peakHours: '7:00 AM - 8:00 AM',
    parking: '361 spaces at the Van Dorn Metro park-and-ride.',
    linesFrom: ['L\'Enfant Plaza', '14th Street', '18th Street'],
    linesTo: ['L\'Enfant Plaza', '14th & Madison Ave', '19th & F Street'],
    notes: 'Legacy-only: present in the /slug_pickup/ inventory, absent from the curated live directory. Marked [Inactive] on the legacy page. No coordinates on the legacy page.',
  },
  {
    slug: 'landmark-mall',
    routeSlug: 'landmark-mall',
    name: 'Landmark Mall',
    corridor: 'I-395 / I-95',
    direction: 'Morning',
    county: 'Fairfax / Alexandria',
    destination: 'L\'Enfant Plaza, 14th Street, and 18th Street',
    description: 'Bus stop #4000576 on the Landmark Mall roadway. The legacy page title carries an explicit [Inactive] marker.',
    latitude: null,
    longitude: null,
    active: false,
    provenance: {
      state: 'needs-review',
      source: 'sluglines.com WordPress export (legacy site; its own content predates 2020)',
    },
    peakHours: '7:00 AM - 8:00 AM',
    parking: 'Lower level of the Landmark Mall garage, rows K-O, next to bus stop #4000576. An Alexandria permit was required.',
    linesFrom: ['L\'Enfant Plaza', '14th Street', '18th Street'],
    fbUrl: 'https://www.facebook.com/groups/dcsluglines/',
    notes: 'Legacy-only: present in the /slug_pickup/ inventory, absent from the curated live directory. Marked [Inactive] on the legacy page. No coordinates on the legacy page.',
  },
  {
    slug: 'route-3-gordon-rd',
    routeSlug: 'Route-3-Gordon-Rd',
    name: 'Route 3 - Gordon Rd',
    corridor: 'I-395 / I-95',
    direction: 'Morning',
    county: 'Stafford / Fredericksburg',
    destination: 'Pentagon, L\'Enfant Plaza, and 14th Street',
    description: 'Route 3 - Gordon Rd is a morning slug line location in Stafford / Fredericksburg serving the I-395 / I-95 corridor.',
    latitude: 38.2895891,
    longitude: -77.5634542,
    active: true,
    provenance: {
      state: 'needs-review',
      source: 'sluglines.com WordPress export (legacy site; its own content predates 2020)',
    },
    peakHours: '5:30 AM - 7:30 AM',
  },
  {
    slug: 'route-17',
    routeSlug: 'Route-17',
    name: 'Route 17',
    corridor: 'I-395 / I-95',
    direction: 'Morning',
    county: 'Stafford / Fredericksburg',
    destination: 'Pentagon, L\'Enfant Plaza, and 14th Street',
    description: 'Route 17 is a morning slug line location in Stafford / Fredericksburg serving the I-395 / I-95 corridor.',
    latitude: 38.3461443,
    longitude: -77.5018604,
    active: true,
    provenance: {
      state: 'needs-review',
      source: 'sluglines.com WordPress export (legacy site; its own content predates 2020)',
    },
    peakHours: '5:30 AM - 7:30 AM',
  },
  {
    slug: 'route-208',
    routeSlug: 'Route-208',
    name: 'Route 208',
    corridor: 'I-395 / I-95',
    direction: 'Morning',
    county: 'Stafford / Fredericksburg',
    destination: 'Pentagon, downtown DC, and Northern Virginia commuter destinations',
    description: 'Route 208 is a morning slug line location in Stafford / Fredericksburg serving the I-395 / I-95 corridor.',
    latitude: 38.25132,
    longitude: -77.508324,
    active: false,
    provenance: {
      state: 'needs-review',
      source: 'sluglines.com WordPress export (legacy site; its own content predates 2020)',
    },
  },
  {
    slug: 'dale-city',
    routeSlug: 'Dale-City',
    name: 'Dale City',
    corridor: 'I-395 / I-95',
    direction: 'Morning',
    county: 'Prince William',
    destination: 'Pentagon, downtown DC, and Northern Virginia commuter destinations',
    description: 'Dale City is a morning slug line location in Prince William serving the I-395 / I-95 corridor.',
    latitude: 38.646938,
    longitude: -77.341232,
    active: false,
    provenance: {
      state: 'needs-review',
      source: 'sluglines.com WordPress export (legacy site; its own content predates 2020)',
    },
  },
  {
    slug: 'horner-rd',
    routeSlug: 'Horner-Rd',
    name: 'Horner Rd',
    corridor: 'I-395 / I-95',
    direction: 'Morning',
    county: 'Prince William',
    destination: 'Pentagon, L\'Enfant Plaza, and 14th Street',
    description: 'Horner Rd is a morning slug line location in Prince William serving the I-395 / I-95 corridor.',
    latitude: 38.658592,
    longitude: -77.280746,
    active: true,
    provenance: {
      state: 'needs-review',
      source: 'sluglines.com WordPress export (legacy site; its own content predates 2020)',
    },
    peakHours: '6:00 AM - 8:30 AM',
    linesFrom: ['Pentagon', 'L\'Enfant Plaza', '14th Street'],
  },
  {
    slug: 'montclair-fire-station',
    routeSlug: 'Montclair-Fire-Station',
    name: 'Montclair Fire Station',
    corridor: 'I-395 / I-95',
    direction: 'Morning',
    county: 'Prince William',
    destination: 'Pentagon, L\'Enfant Plaza, and 14th Street',
    description: 'Montclair Fire Station is a morning slug line location in Prince William serving the I-395 / I-95 corridor.',
    latitude: 38.62624,
    longitude: -77.348183,
    active: true,
    provenance: {
      state: 'needs-review',
      source: 'sluglines.com WordPress export (legacy site; its own content predates 2020)',
    },
    peakHours: '6:00 AM - 8:30 AM',
    fbUrl: 'https://www.facebook.com/groups/montclairslugs/',
  },
  {
    slug: 'montclair-northgate',
    routeSlug: 'Montclair-Northgate',
    name: 'Montclair Northgate',
    corridor: 'I-395 / I-95',
    direction: 'Morning',
    county: 'Prince William',
    destination: 'Pentagon, L\'Enfant Plaza, and 14th Street',
    description: 'Montclair Northgate is a morning slug line location in Prince William serving the I-395 / I-95 corridor.',
    latitude: 38.6105087,
    longitude: -77.359309,
    active: true,
    provenance: {
      state: 'needs-review',
      source: 'sluglines.com WordPress export (legacy site; its own content predates 2020)',
    },
    peakHours: '6:00 AM - 8:30 AM',
    fbUrl: 'https://www.facebook.com/groups/montclairslugs/',
  },
  {
    slug: 'old-hechingers',
    routeSlug: 'Old-Hechingers',
    name: 'Old Hechingers',
    corridor: 'I-395 / I-95',
    direction: 'Morning',
    county: 'Prince William',
    destination: 'Pentagon, L\'Enfant Plaza, and 14th Street',
    description: 'Old Hechingers is a morning slug line location in Prince William serving the I-395 / I-95 corridor.',
    latitude: 38.674301,
    longitude: -77.255623,
    active: true,
    provenance: {
      state: 'needs-review',
      source: 'sluglines.com WordPress export (legacy site; its own content predates 2020)',
    },
    peakHours: '6:00 AM - 8:30 AM',
  },
  {
    slug: 'potomac-mills',
    routeSlug: 'Potomac-Mills',
    name: 'Potomac Mills',
    corridor: 'I-395 / I-95',
    direction: 'Morning',
    county: 'Prince William',
    destination: 'Pentagon, Crystal City, Rosslyn, and DC',
    description: 'Potomac Mills is a morning slug line location in Prince William serving the I-395 / I-95 corridor.',
    latitude: 38.640717,
    longitude: -77.293884,
    active: true,
    provenance: {
      state: 'needs-review',
      source: 'sluglines.com WordPress export (legacy site; its own content predates 2020)',
    },
    peakHours: '6:30 AM - 8:15 AM',
    parking: 'Commuter parking around Potomac Mills Circle.',
    linesTo: ['The Pentagon', '15th Street & New York Ave', 'Rosslyn'],
    fbUrl: 'https://www.facebook.com/groups/potomacmillssluglines/',
  },
  {
    slug: 'route-123',
    routeSlug: 'Route-123',
    name: 'Route 123',
    corridor: 'I-395 / I-95',
    direction: 'Morning',
    county: 'Prince William',
    destination: 'Pentagon, L\'Enfant Plaza, and 14th Street',
    description: 'Route 123 is a morning slug line location in Prince William serving the I-395 / I-95 corridor.',
    latitude: 38.6701716,
    longitude: -77.2509748,
    active: true,
    provenance: {
      state: 'needs-review',
      source: 'sluglines.com WordPress export (legacy site; its own content predates 2020)',
    },
    peakHours: '6:00 AM - 8:30 AM',
  },
  {
    slug: 'route-234',
    routeSlug: 'Route-234',
    name: 'Route 234',
    corridor: 'I-395 / I-95',
    direction: 'Morning',
    county: 'Prince William',
    destination: 'Pentagon, L\'Enfant Plaza, and 14th Street',
    description: 'Route 234 is a morning slug line location in Prince William serving the I-395 / I-95 corridor.',
    latitude: 38.576817,
    longitude: -77.315826,
    active: true,
    provenance: {
      state: 'needs-review',
      source: 'sluglines.com WordPress export (legacy site; its own content predates 2020)',
    },
    peakHours: '5:45 AM - 8:00 AM',
  },
  {
    slug: 'tacketts-mill',
    routeSlug: 'Tacketts-Mill',
    name: 'Tacketts Mill',
    corridor: 'I-395 / I-95',
    direction: 'Morning',
    county: 'Prince William',
    destination: 'Pentagon, L\'Enfant Plaza, and 14th Street',
    description: 'Tacketts Mill is a morning slug line location in Prince William serving the I-395 / I-95 corridor.',
    latitude: 38.675777,
    longitude: -77.276543,
    active: true,
    provenance: {
      state: 'needs-review',
      source: 'sluglines.com WordPress export (legacy site; its own content predates 2020)',
    },
    peakHours: '6:00 AM - 8:30 AM',
  },
  {
    slug: 'telegraph-rd',
    routeSlug: 'Telegraph-Rd',
    name: 'Telegraph Rd',
    corridor: 'I-395 / I-95',
    direction: 'Morning',
    county: 'Prince William',
    destination: 'Pentagon, L\'Enfant Plaza, and 14th Street',
    description: 'Telegraph Rd is a morning slug line location in Prince William serving the I-395 / I-95 corridor.',
    latitude: 38.658051,
    longitude: -77.288749,
    active: true,
    provenance: {
      state: 'needs-review',
      source: 'sluglines.com WordPress export (legacy site; its own content predates 2020)',
    },
    peakHours: '6:00 AM - 8:30 AM',
  },
  {
    slug: 'route-610-mine-rd',
    routeSlug: 'Route-610-Mine-Rd',
    name: 'Route 610 - Mine Rd',
    corridor: 'I-395 / I-95',
    direction: 'Morning',
    county: 'Stafford / Fredericksburg',
    destination: 'Pentagon and L\'Enfant Plaza',
    description: 'Route 610 - Mine Rd is a morning slug line location in Stafford / Fredericksburg serving the I-395 / I-95 corridor.',
    latitude: 38.4669945,
    longitude: -77.4160618,
    active: true,
    provenance: {
      state: 'needs-review',
      source: 'sluglines.com WordPress export (legacy site; its own content predates 2020)',
    },
    peakHours: '5:30 AM - 7:30 AM',
  },
  {
    slug: 'route-610-staffordboro-blvd',
    routeSlug: 'Route-610-Staffordboro-Blvd',
    name: 'Route 610 - Staffordboro Blvd',
    corridor: 'I-395 / I-95',
    direction: 'Morning',
    county: 'Stafford / Fredericksburg',
    destination: 'Pentagon and L\'Enfant Plaza',
    description: 'Route 610 - Staffordboro Blvd is a morning slug line location in Stafford / Fredericksburg serving the I-395 / I-95 corridor.',
    latitude: 38.4752647,
    longitude: -77.4129771,
    active: true,
    provenance: {
      state: 'needs-review',
      source: 'sluglines.com WordPress export (legacy site; its own content predates 2020)',
    },
    peakHours: '5:30 AM - 7:30 AM',
  },
  {
    slug: 'route-630',
    routeSlug: 'Route-630',
    name: 'Route 630',
    corridor: 'I-395 / I-95',
    direction: 'Morning',
    county: 'Stafford / Fredericksburg',
    destination: 'Pentagon and L\'Enfant Plaza',
    description: 'Route 630 is a morning slug line location in Stafford / Fredericksburg serving the I-395 / I-95 corridor.',
    latitude: 38.4212359,
    longitude: -77.4254927,
    active: true,
    provenance: {
      state: 'needs-review',
      source: 'sluglines.com WordPress export (legacy site; its own content predates 2020)',
    },
    peakHours: '5:30 AM - 7:30 AM',
  },
  {
    slug: 'mark-center',
    routeSlug: 'Mark-Center',
    name: 'Mark Center',
    corridor: 'I-395 / I-95',
    direction: 'Afternoon',
    county: 'Fairfax / Alexandria',
    destination: 'Springfield, Lorton, and Fairfax-area lines',
    description: 'Mark Center is a afternoon slug line location in Fairfax / Alexandria serving the I-395 / I-95 corridor.',
    latitude: 38.8310454,
    longitude: -77.1176246,
    active: true,
    provenance: {
      state: 'needs-review',
      source: 'sluglines.com WordPress export (legacy site; its own content predates 2020)',
    },
    peakHours: '3:30 PM - 6:30 PM',
    fbUrl: 'https://www.facebook.com/groups/markcenterslugs/',
  },
  {
    slug: 'tysons-corner',
    routeSlug: 'Tysons-Corner',
    name: 'Tysons Corner',
    corridor: 'I-395 / I-95',
    direction: 'Afternoon',
    county: 'Fairfax / Alexandria',
    destination: 'Fairfax and Springfield-area lines',
    description: 'Tysons Corner is a afternoon slug line location in Fairfax / Alexandria serving the I-395 / I-95 corridor.',
    latitude: 38.931906,
    longitude: -77.230132,
    active: true,
    provenance: {
      state: 'needs-review',
      source: 'sluglines.com WordPress export (legacy site; its own content predates 2020)',
    },
    peakHours: '3:30 PM - 6:30 PM',
  },
  {
    slug: 'crystal-city-12th-st',
    routeSlug: 'Crystal-City-12th-St',
    name: 'Crystal City 12th St',
    corridor: 'I-395 / I-95',
    direction: 'Afternoon',
    county: 'Arlington',
    destination: 'Fairfax, Prince William, and Stafford',
    description: 'Crystal City 12th St is a afternoon slug line location in Arlington serving the I-395 / I-95 corridor.',
    latitude: 38.8620732,
    longitude: -77.048738,
    active: true,
    provenance: {
      state: 'needs-review',
      source: 'sluglines.com WordPress export (legacy site; its own content predates 2020)',
    },
    peakHours: '3:30 PM - 6:30 PM',
    fbUrl: 'https://www.facebook.com/groups/crystalcitysluglines/',
    image: {
      src: '/spots/Crystal_City_12th_St.jpg',
      width: 460,
      height: 421,
      alt: 'Transit diagram for Crystal City 12th St, republished from the legacy sluglines.com page for this spot.',
      sourceUrl: 'https://sluglines.com/images/slugging_locations/Crystal_City_12th_St.jpg',
      fetchedAt: '2026-08-22',
    },
  },
  {
    slug: 'crystal-city-23rd-st',
    routeSlug: 'Crystal-City-23rd-St',
    name: 'Crystal City 23rd St',
    corridor: 'I-395 / I-95',
    direction: 'Afternoon',
    county: 'Arlington',
    destination: 'Fairfax, Prince William, and Stafford',
    description: 'Crystal City 23rd St is a afternoon slug line location in Arlington serving the I-395 / I-95 corridor.',
    latitude: 38.85238,
    longitude: -77.04964,
    active: true,
    provenance: {
      state: 'needs-review',
      source: 'sluglines.com WordPress export (legacy site; its own content predates 2020)',
    },
    peakHours: '3:30 PM - 6:30 PM',
    fbUrl: 'https://www.facebook.com/groups/crystalcitysluglines/',
    image: {
      src: '/spots/Crystal_City_12th_St.jpg',
      width: 460,
      height: 421,
      alt: 'Transit diagram for Crystal City 23rd St, republished from the legacy sluglines.com page for this spot.',
      sourceUrl: 'https://sluglines.com/images/slugging_locations/Crystal_City_12th_St.jpg',
      fetchedAt: '2026-08-22',
    },
  },
  {
    slug: 'rosslyn',
    routeSlug: 'Rosslyn',
    name: 'Rosslyn',
    corridor: 'I-395 / I-95',
    direction: 'Afternoon',
    county: 'Arlington',
    destination: 'Northern Virginia corridors',
    description: 'Rosslyn is a afternoon slug line location in Arlington serving the I-395 / I-95 corridor.',
    latitude: 38.898092,
    longitude: -77.071726,
    active: true,
    provenance: {
      state: 'needs-review',
      source: 'sluglines.com WordPress export (legacy site; its own content predates 2020)',
    },
    peakHours: '3:30 PM - 6:30 PM',
    fbUrl: 'https://www.facebook.com/groups/rosslynsluglines/',
  },
  {
    slug: 'the-pentagon',
    routeSlug: 'The-Pentagon',
    name: 'The Pentagon',
    corridor: 'I-395 / I-95',
    direction: 'Afternoon',
    county: 'Arlington',
    destination: 'All Northern Virginia corridors',
    description: 'The Pentagon is a afternoon slug line location in Arlington serving the I-395 / I-95 corridor.',
    latitude: 38.8680768,
    longitude: -77.0524506,
    active: true,
    provenance: {
      state: 'needs-review',
      source: 'sluglines.com WordPress export (legacy site; its own content predates 2020)',
    },
    peakHours: '3:30 PM - 6:30 PM',
    fbUrl: 'https://www.facebook.com/groups/pentagonsluglines/',
  },
  {
    slug: '14th-st-and-constitution-ave',
    routeSlug: '14th-St-and-Constitution-Ave',
    name: '14th St and Constitution Ave',
    corridor: 'I-395 / I-95',
    direction: 'Afternoon',
    county: 'Washington DC',
    destination: 'Northern Virginia commuter lots',
    description: '14th St and Constitution Ave is a afternoon slug line location in Washington DC serving the I-395 / I-95 corridor.',
    latitude: 38.889938,
    longitude: -77.032021,
    active: true,
    provenance: {
      state: 'needs-review',
      source: 'sluglines.com WordPress export (legacy site; its own content predates 2020)',
    },
  },
  {
    slug: '14th-st-and-g-st',
    routeSlug: '14th-St-and-G-St',
    name: '14th St and G St',
    corridor: 'I-395 / I-95',
    direction: 'Afternoon',
    county: 'Washington DC',
    destination: 'Northern Virginia commuter lots',
    description: '14th St and G St is a afternoon slug line location in Washington DC serving the I-395 / I-95 corridor.',
    latitude: 38.8981415,
    longitude: -77.0320751,
    active: true,
    provenance: {
      state: 'needs-review',
      source: 'sluglines.com WordPress export (legacy site; its own content predates 2020)',
    },
  },
  {
    slug: '14th-st-and-independence',
    routeSlug: '14th-St-and-Independence',
    name: '14th St and Independence',
    corridor: 'I-395 / I-95',
    direction: 'Afternoon',
    county: 'Washington DC',
    destination: 'Northern Virginia commuter lots',
    description: '14th St and Independence is a afternoon slug line location in Washington DC serving the I-395 / I-95 corridor.',
    latitude: 38.88733,
    longitude: -77.032156,
    active: true,
    provenance: {
      state: 'needs-review',
      source: 'sluglines.com WordPress export (legacy site; its own content predates 2020)',
    },
  },
  {
    slug: '14th-st-at-commerce-dept',
    routeSlug: '14th-St-at-Commerce-Dept',
    name: '14th St at Commerce Dept.',
    corridor: 'I-395 / I-95',
    direction: 'Afternoon',
    county: 'Washington DC',
    destination: 'Northern Virginia commuter lots',
    description: '14th St at Commerce Dept. is a afternoon slug line location in Washington DC serving the I-395 / I-95 corridor.',
    latitude: 38.89462,
    longitude: -77.03207,
    active: true,
    provenance: {
      state: 'needs-review',
      source: 'sluglines.com WordPress export (legacy site; its own content predates 2020)',
    },
    image: {
      src: '/spots/14th_St_at_Commerce_Dept.jpg',
      width: 460,
      height: 396,
      alt: 'Transit diagram for 14th St at Commerce Dept., republished from the legacy sluglines.com page for this spot.',
      sourceUrl: 'https://sluglines.com/images/slugging_locations/14th_St_at_Commerce_Dept.jpg',
      fetchedAt: '2026-08-22',
    },
  },
  {
    slug: '15th-st-and-new-york-ave',
    routeSlug: '15th-St-and-New-York-Ave',
    name: '15th St and New York Ave',
    corridor: 'I-395 / I-95',
    direction: 'Afternoon',
    county: 'Washington DC',
    destination: 'Northern Virginia commuter lots',
    description: '15th St and New York Ave is a afternoon slug line location in Washington DC serving the I-395 / I-95 corridor.',
    latitude: 38.8990078,
    longitude: -77.033381,
    active: true,
    provenance: {
      state: 'needs-review',
      source: 'sluglines.com WordPress export (legacy site; its own content predates 2020)',
    },
  },
  {
    slug: '19th-st-and-f-st',
    routeSlug: '19th-St-and-F-St',
    name: '19th St and F St',
    corridor: 'I-395 / I-95',
    direction: 'Afternoon',
    county: 'Washington DC',
    destination: 'Northern Virginia commuter lots',
    description: '19th St and F St is a afternoon slug line location in Washington DC serving the I-395 / I-95 corridor.',
    latitude: 38.896695,
    longitude: -77.043543,
    active: true,
    provenance: {
      state: 'needs-review',
      source: 'sluglines.com WordPress export (legacy site; its own content predates 2020)',
    },
  },
  {
    slug: '19th-st-and-i-st',
    routeSlug: '19th-St-and-I-St',
    name: '19th St and I St',
    corridor: 'I-395 / I-95',
    direction: 'Afternoon',
    county: 'Washington DC',
    destination: 'Northern Virginia commuter lots',
    description: '19th St and I St is a afternoon slug line location in Washington DC serving the I-395 / I-95 corridor.',
    latitude: 38.900711,
    longitude: -77.043549,
    active: true,
    provenance: {
      state: 'needs-review',
      source: 'sluglines.com WordPress export (legacy site; its own content predates 2020)',
    },
  },
  {
    slug: 'lenfant-plaza',
    routeSlug: 'LEnfant-Plaza',
    name: 'L\'Enfant Plaza',
    corridor: 'I-395 / I-95',
    direction: 'Afternoon',
    county: 'Washington DC',
    destination: 'Fairfax, Prince William, and Stafford',
    description: 'L\'Enfant Plaza is a afternoon slug line location in Washington DC serving the I-395 / I-95 corridor.',
    latitude: 38.88489,
    longitude: -77.023402,
    active: true,
    provenance: {
      state: 'needs-review',
      source: 'sluglines.com WordPress export (legacy site; its own content predates 2020)',
    },
    peakHours: '3:30 PM - 6:30 PM',
    fbUrl: 'https://www.facebook.com/groups/lenfantslugs/',
  },
  {
    slug: 'navy-yard',
    routeSlug: 'Navy-Yard',
    name: 'Navy Yard',
    corridor: 'I-395 / I-95',
    direction: 'Afternoon',
    county: 'Washington DC',
    destination: 'Northern Virginia commuter lots',
    description: 'Navy Yard is a afternoon slug line location in Washington DC serving the I-395 / I-95 corridor.',
    latitude: 38.8765811,
    longitude: -77.0014703,
    active: true,
    provenance: {
      state: 'needs-review',
      source: 'sluglines.com WordPress export (legacy site; its own content predates 2020)',
    },
  },
  {
    slug: 'state-department',
    routeSlug: 'state-department',
    name: 'State Department',
    corridor: 'I-395 / I-95',
    direction: 'Afternoon',
    county: 'Washington DC',
    destination: 'Horner Rd and Telegraph Rd',
    description: 'A proposed pickup point the legacy page describes as "a new pickup location ... still explored". Its own comment thread records that the line never formed.',
    latitude: null,
    longitude: null,
    active: false,
    provenance: {
      state: 'needs-review',
      source: 'sluglines.com WordPress export (legacy site; its own content predates 2020)',
    },
    linesFrom: ['Horner Rd', 'Telegraph Rd'],
    linesTo: ['Horner Rd', 'Telegraph Rd'],
    fbUrl: 'https://www.facebook.com/groups/dcsluglines/',
    notes: 'Legacy-only: present in the /slug_pickup/ inventory, absent from the curated live directory. Never operated. No coordinates on the legacy page.',
  },
  {
    slug: 'vienna-metro-south-knr',
    routeSlug: 'Vienna-Metro-South-KnR',
    name: 'Vienna Metro South KnR',
    corridor: 'I-66',
    direction: 'Morning',
    county: 'Fairfax',
    destination: 'Pentagon, Rosslyn, and L\'Enfant Plaza',
    description: 'Vienna Metro South KnR is a morning slug line location in Fairfax serving the I-66 corridor.',
    latitude: 38.8774069,
    longitude: -77.2706202,
    active: true,
    provenance: {
      state: 'needs-review',
      source: 'Directory addition for the I-66 corridor; no primary source recorded',
    },
    peakHours: '6:00 AM - 8:30 AM',
    fbUrl: 'https://www.facebook.com/groups/viennaslugs/',
  },
  {
    slug: 'fairfax-govt',
    routeSlug: 'Fairfax-Govt',
    name: 'Fairfax Govt',
    corridor: 'I-66',
    direction: 'Morning',
    county: 'Fairfax',
    destination: 'Pentagon, Rosslyn, and L\'Enfant Plaza',
    description: 'Fairfax Govt is a morning slug line location in Fairfax serving the I-66 corridor.',
    latitude: 38.8542902,
    longitude: -77.3604273,
    active: true,
    provenance: {
      state: 'needs-review',
      source: 'Directory addition for the I-66 corridor; no primary source recorded',
    },
    peakHours: '6:00 AM - 8:30 AM',
  },
  {
    slug: 'stringfellow-pnr',
    routeSlug: 'Stringfellow-PnR',
    name: 'Stringfellow PnR',
    corridor: 'I-66',
    direction: 'Morning',
    county: 'Fairfax',
    destination: 'Pentagon, Rosslyn, and L\'Enfant Plaza',
    description: 'Stringfellow PnR is a morning slug line location in Fairfax serving the I-66 corridor.',
    latitude: 38.854028,
    longitude: -77.404472,
    active: true,
    provenance: {
      state: 'needs-review',
      source: 'Directory addition for the I-66 corridor; no primary source recorded',
    },
    peakHours: '6:00 AM - 8:30 AM',
  },
  {
    slug: 'herndon-monroe-pnr',
    routeSlug: 'Herndon-Monroe-PnR',
    name: 'Herndon-Monroe PnR',
    corridor: 'I-66',
    direction: 'Morning',
    county: 'Fairfax',
    destination: 'Pentagon, Rosslyn, and L\'Enfant Plaza',
    description: 'Herndon-Monroe PnR is a morning slug line location in Fairfax serving the I-66 corridor.',
    latitude: 38.9513106,
    longitude: -77.3823065,
    active: true,
    provenance: {
      state: 'needs-review',
      source: 'Directory addition for the I-66 corridor; no primary source recorded',
    },
    peakHours: '6:00 AM - 8:30 AM',
  },
  {
    slug: 'cushing-road',
    routeSlug: 'Cushing-Road',
    name: 'Cushing Road',
    corridor: 'I-66',
    direction: 'Morning',
    county: 'Prince William',
    destination: 'Pentagon, Rosslyn, and L\'Enfant Plaza',
    description: 'Cushing Road is a morning slug line location in Prince William serving the I-66 corridor.',
    latitude: 38.7950597,
    longitude: -77.563859,
    active: true,
    provenance: {
      state: 'needs-review',
      source: 'Directory addition for the I-66 corridor; no primary source recorded',
    },
    peakHours: '5:45 AM - 8:00 AM',
  },
  {
    slug: 'east-gate',
    routeSlug: 'East-Gate',
    name: 'East Gate',
    corridor: 'I-66',
    direction: 'Morning',
    county: 'Loudoun',
    destination: 'Pentagon, Rosslyn, and L\'Enfant Plaza',
    description: 'East Gate is a morning slug line location in Loudoun serving the I-66 corridor.',
    latitude: 38.9119294,
    longitude: -77.4914467,
    active: true,
    provenance: {
      state: 'needs-review',
      source: 'Directory addition for the I-66 corridor; no primary source recorded',
    },
    peakHours: '5:45 AM - 8:00 AM',
  },
  {
    slug: 'stone-ridge',
    routeSlug: 'Stone-Ridge',
    name: 'Stone Ridge',
    corridor: 'I-66',
    direction: 'Morning',
    county: 'Loudoun',
    destination: 'Pentagon, Rosslyn, and L\'Enfant Plaza',
    description: 'Stone Ridge is a morning slug line location in Loudoun serving the I-66 corridor.',
    latitude: 38.938222,
    longitude: -77.555917,
    active: true,
    provenance: {
      state: 'needs-review',
      source: 'Directory addition for the I-66 corridor; no primary source recorded',
    },
    peakHours: '5:45 AM - 8:00 AM',
  },
  {
    slug: 'foggy-bottom',
    routeSlug: 'Foggy-Bottom',
    name: 'Foggy Bottom',
    corridor: 'I-66',
    direction: 'Afternoon',
    county: 'Washington DC',
    destination: 'Fairfax, Loudoun, and Prince William I-66 lines',
    description: 'Foggy Bottom is a afternoon slug line location in Washington DC serving the I-66 corridor.',
    latitude: 38.90075,
    longitude: -77.049611,
    active: true,
    provenance: {
      state: 'needs-review',
      source: 'Directory addition for the I-66 corridor; no primary source recorded',
    },
    peakHours: '3:30 PM - 6:30 PM',
  },
]

/** Asserted against the seeded row count by the migration and by its test. */
export const SPOT_LOCATION_COUNT = SPOT_LOCATIONS.length

const BY_SLUG: ReadonlyMap<string, SpotLocation> = new Map(
  SPOT_LOCATIONS.map((location) => [location.slug, location])
)

/**
 * Slugs are compared case-insensitively everywhere. The legacy site used
 * lower-case URLs and this app serves mixed case, so a caller may hold either.
 */
export function canonicalSlug(slug: string) {
  return slug.trim().toLowerCase()
}

export function findSpotLocation(slug: string): SpotLocation | undefined {
  return BY_SLUG.get(canonicalSlug(slug))
}

export function hasSpotLocation(slug: string) {
  return BY_SLUG.has(canonicalSlug(slug))
}

export function activeSpotLocations() {
  return SPOT_LOCATIONS.filter((location) => location.active)
}

export function inactiveSpotLocations() {
  return SPOT_LOCATIONS.filter((location) => !location.active)
}

export function spotLocationsByCorridor(corridor: SpotCorridor) {
  return SPOT_LOCATIONS.filter((location) => location.corridor === corridor)
}

export function spotLocationsByDirection(direction: SpotDirection) {
  return SPOT_LOCATIONS.filter((location) => location.direction === direction)
}

export function spotLocationCounties(locations: readonly SpotLocation[] = SPOT_LOCATIONS) {
  return Array.from(new Set(locations.map((location) => location.county)))
}

export interface SpotLocationCorridorGroup {
  corridor: SpotCorridor
  directions: {
    direction: SpotDirection
    counties: { county: string; locations: SpotLocation[] }[]
  }[]
}

/**
 * Corridor → direction → county, with empty groups dropped. Directions are
 * emitted in `SPOT_DIRECTIONS` order (Morning before Afternoon) rather than in
 * first-seen order, because that is a commute-day ordering and not a data one.
 */
export function groupSpotLocations(
  locations: readonly SpotLocation[] = SPOT_LOCATIONS
): SpotLocationCorridorGroup[] {
  const corridors = SPOT_CORRIDORS.filter((corridor) =>
    locations.some((location) => location.corridor === corridor)
  )

  return corridors.map((corridor) => ({
    corridor,
    directions: SPOT_DIRECTIONS.map((direction) => {
      const inDirection = locations.filter(
        (location) => location.corridor === corridor && location.direction === direction
      )

      return {
        direction,
        counties: spotLocationCounties(inDirection).map((county) => ({
          county,
          locations: inDirection.filter((location) => location.county === county),
        })),
      }
    }).filter((group) => group.counties.length > 0),
  }))
}

export interface SpotCoordinates {
  latitude: number
  longitude: number
}

const EARTH_RADIUS_MILES = 3958.8

function toRadians(value: number) {
  return (value * Math.PI) / 180
}

export function distanceInMiles(from: SpotCoordinates, to: SpotCoordinates) {
  const latitudeDistance = toRadians(to.latitude - from.latitude)
  const longitudeDistance = toRadians(to.longitude - from.longitude)

  const haversine =
    Math.sin(latitudeDistance / 2) ** 2 +
    Math.cos(toRadians(from.latitude)) *
      Math.cos(toRadians(to.latitude)) *
      Math.sin(longitudeDistance / 2) ** 2

  return EARTH_RADIUS_MILES * 2 * Math.atan2(Math.sqrt(haversine), Math.sqrt(1 - haversine))
}

/**
 * Distance from `origin`, or `Infinity` for a spot with no surveyed coordinate.
 * `Infinity` rather than `null` so it sorts last without a special case at every
 * call site — an uncoordinated spot is never the nearest one.
 */
export function spotLocationDistance(location: SpotLocation, origin: SpotCoordinates) {
  if (location.latitude === null || location.longitude === null) {
    return Number.POSITIVE_INFINITY
  }

  return distanceInMiles(origin, { latitude: location.latitude, longitude: location.longitude })
}

export function nearestSpotLocations(
  origin: SpotCoordinates,
  options: { limit?: number; locations?: readonly SpotLocation[] } = {}
) {
  const { limit, locations = SPOT_LOCATIONS } = options

  const ranked = locations
    .map((location) => ({ location, miles: spotLocationDistance(location, origin) }))
    .filter((entry) => Number.isFinite(entry.miles))
    .sort((left, right) => left.miles - right.miles)

  return typeof limit === 'number' ? ranked.slice(0, limit) : ranked
}
