/**
 * `lib/domain/locations.ts` — the spot location directory (rev. 5.3 §11 P1).
 *
 * This module is the **single source of truth** for the spot inventory. Three
 * things are generated from or checked against it, and none of them owns a copy:
 *
 *   - `supabase/migrations/0004_spot_locations_directory.sql` — generated by
 *     `scripts/seed-locations.mjs`, which `tests/spot-locations-directory.test.mjs`
 *     re-runs and compares byte-for-byte against the committed file. The SQL and
 *     this array therefore cannot drift apart without a red test.
 *   - `src/lib/spot-directory.ts` — the presentation adapter. It maps this array
 *     into the `DirectorySpot` shape the existing components consume; it no
 *     longer holds spot data.
 *   - the legacy `/slug_pickup/**` inventory in `src/data/legacy-site-content.json`,
 *     every spot slug of which must appear below (same test).
 *
 * BOUNDARY (rev. 5.3 §8, enforced by `tests/domain-boundaries.test.mjs`)
 * ---------------------------------------------------------------------------
 * `lib/domain/**` imports `lib/supabase` only — never React, never `lib/ai`. So
 * the inventory lives here as committed data rather than being read from the
 * legacy JSON at runtime: the domain layer does not reach outward, and a
 * directory that a rendering module could edit is not a directory.
 *
 * SLUGS: `slug` vs. `routeSlug`
 * ---------------------------------------------------------------------------
 * `slug` is the canonical lower-case key. It is what the database stores, what
 * the legacy `/slug_pickup/<slug>/` URLs used, and what every lookup normalises
 * to. `routeSlug` preserves the historical casing this app already serves at
 * `/spots/<routeSlug>` (e.g. `Horner-Rd`). They differ only in case, but the
 * distinction is load-bearing: collapsing them would change live URLs, and
 * collapsing them the other way would make the database key case-sensitive.
 *
 * COORDINATES ARE NULLABLE, DELIBERATELY
 * ---------------------------------------------------------------------------
 * Four spots carry `latitude: null, longitude: null` — the four that exist only
 * in the legacy inventory. Their legacy pages publish no coordinates, and this
 * repo does not invent data. `null` is the honest value; a plausible-looking
 * guess would be indistinguishable from a surveyed one. See `Docs/DECISIONS.md`
 * D-31.
 */

export type SpotCorridor = 'I-395 / I-95' | 'I-66'
export type SpotDirection = 'Morning' | 'Afternoon'

/**
 * A spot's media asset, self-hosted. **A transit diagram, not a photograph.**
 *
 * NOT a database column, deliberately. `0004_spot_locations_directory.sql` is
 * generated from this file by `scripts/seed-locations.mjs` and guarded
 * byte-for-byte, so a field that entered `SEED_COLUMNS` would regenerate it.
 * Nothing queries by image and no RLS decision attaches to a static asset path,
 * so this lives in the domain module and `0004` applies untouched (issue #18).
 *
 * `src` is always a path under `public/`. Never a remote URL: a hotlink to
 * sluglines.com dies the day WordPress is cancelled, which is the point of the
 * migration.
 *
 * WHAT THESE FILES ARE, AND WHAT THEY ARE NOT
 * ---------------------------------------------------------------------------
 * `Docs/asset-register.md` classifies all 27 legacy assets: 12 Google Maps
 * aerials, 8 third-party transit or parking schematics, 6 dated route-change
 * notices, 1 promotional flyer, and **zero photographs of a location**. D-39
 * declined to migrate any of them. D-58 migrates **only the 8 schematics** —
 * drawn agency lot diagrams with bus-bay listings, space counts and legends —
 * and holds the other 19 out: the Google aerials carry Google's own credit and
 * its terms, the notices are 2018-2019 and would render as current, and the
 * flyer is a marketing graphic with a contact address on it.
 *
 * So this field is a **transit diagram**, never a photograph. A diagram of a lot
 * is useful orientation; the same file captioned as a photograph would claim a
 * currency and an authorship it does not have — the same failure as a guessed
 * coordinate (D-31) or a fabricated count (D-33). #26 still tracks sourcing real
 * photographs, and this field is not it.
 */
export interface SpotImage {
  /** Path under `public/`, e.g. `/spots/horner-rd.jpg`. Never a remote URL. */
  src: string
  /** Intrinsic pixel size, so `next/image` reserves the box and CLS stays at 0. */
  width: number
  height: number
  /** Describes the spot for a screen reader, not the file. */
  alt: string
  /** Provenance: the legacy URL this file came from. Asserted against LEGACY_IMAGE_PREFIX. */
  sourceUrl: string
  /** ISO date the file was pulled from the legacy site. */
  fetchedAt: string
}

export interface SpotLocation {
  /** Canonical lower-case key: the database key and the legacy URL slug. */
  slug: string
  /** Case-preserved path segment this app serves today. */
  routeSlug: string
  name: string
  corridor: SpotCorridor
  direction: SpotDirection
  county: string
  destination: string
  description: string
  /** `null` where no surveyed coordinate exists. Never guessed. */
  latitude: number | null
  longitude: number | null
  /** Whether a line is believed to be running. Inactive spots stay in the directory. */
  active: boolean
  /**
   * Where this record's operational facts came from and how current they are
   * (issue #36). Required, not optional: an unstated provenance is precisely the
   * problem this models — it renders as confidence the record has not earned.
   */
  provenance: SpotProvenance
  peakHours?: string
  parking?: string
  linesFrom?: string[]
  linesTo?: string[]
  fbUrl?: string
  notes?: string
  /** Absent where the legacy page published no diagram. Never a stand-in. */
  image?: SpotImage
}

/**
 * Publication state for a spot's operational facts — `peakHours`, `parking`,
 * `linesFrom`/`linesTo`, `description` (issue #36).
 *
 * Salvaged from `codex/phase-1`'s `Docs/content-sources.md` during the #11
 * triage. The problem it solves is the one this repo already takes seriously
 * everywhere else: a commuter reading "peak hours 5:30–9:00" cannot tell whether
 * that was confirmed last month or scraped from a 2018 post, because the app
 * renders both with identical authority. Null coordinates are never guessed
 * (D-31) and counts render `unavailable` rather than a fabricated zero (D-33);
 * directory facts were the remaining surface with no honesty mechanism.
 *
 *   verified            Confirmed against a current primary source, or a dated
 *                       on-site review by an editor.
 *   community-reported  Recently reported, not yet corroborated by a primary
 *                       source.
 *   needs-review        Useful orientation whose current operation has not been
 *                       confirmed. The honest state for anything inherited.
 *   historical          Retained for context, never presented as current
 *                       instructions.
 *
 * SOURCE HIERARCHY, strongest first: government or transit-operator pages; then
 * current on-site signage confirmed by an editor; then corroborated community
 * reports; then legacy Sluglines material, which is background and discovery
 * only and never on its own sufficient for `verified`.
 */
export type SpotFactState = 'verified' | 'community-reported' | 'needs-review' | 'historical'

export interface SpotProvenance {
  state: SpotFactState
  /** Where the operational facts came from. Free text, but name a real source. */
  source: string
  /**
   * ISO date the facts were last checked against that source — the date of the
   * *check*, not of the import. Absent where no check has ever happened, which is
   * different from a check that found nothing and must not be back-filled with an
   * import date to make the record look attended to.
   */
  checkedAt?: string
}

/**
 * The states whose facts must not be presented as current instructions without a
 * qualifier. `verified` is deliberately absent: a verified fact needs no badge,
 * which is what keeps the badge meaningful rather than decorative.
 */
export function needsFreshnessQualifier(spot: Pick<SpotLocation, 'provenance'>): boolean {
  return spot.provenance.state !== 'verified'
}

/**
 * The only path a migrated image may have come from (issue #18).
 *
 * Deliberately the narrow `slugging_locations/` path and not `images/`. Three
 * spots publish their asset one directory up, and all three are Google Maps
 * aerials that D-58 declined to migrate; widening the prefix to admit them would
 * remove the guard at the moment it was doing its job. Some legacy pages also
 * embed an `lh5.googleusercontent.com` commenter avatar, which is a person, not
 * a spot.
 */
export const LEGACY_IMAGE_PREFIX = 'https://sluglines.com/images/slugging_locations/'

export function spotImage(slug: string): SpotImage | undefined {
  return findSpotLocation(slug)?.image
}

export const SPOT_CORRIDORS: readonly SpotCorridor[] = ['I-395 / I-95', 'I-66']
export const SPOT_DIRECTIONS: readonly SpotDirection[] = ['Morning', 'Afternoon']

/**
 * The directory, ordered corridor → direction → county so the file reads the way
 * the site groups it. Order is not semantic: every consumer groups or filters.
 */
export const SPOT_LOCATIONS: readonly SpotLocation[] = [
  {
    slug: 'bobs-old-keene-mill-rd',
    routeSlug: 'Bobs-Old-Keene-Mill-Rd',
    name: 'Bob\'s - Old Keene Mill Rd',
    corridor: 'I-395 / I-95',
    direction: 'Morning',
    county: 'Fairfax',
    destination: 'Pentagon, L\'Enfant Plaza, and downtown DC',
    description: 'There are 2 slug staging areas at Bobs, primarily going to DC locations at the Keene Mill Park and Ride behind the gas station next to the bus shelter goes to 18th, 20th and 23rd street. The line away from the gas station goes to 14th street and L’Enfant. Bob’s pickup location is closed for construction. For more details check https://sluglines.com/blog/bobs-slug-line-and-parking-relocation-plan/. 14th Street / L’Enfant Plaza lines will be relocated to the Springfield Town Center Garage, join https://www.facebook.com/groups/stcsluglines to coordinate. 18th Street line will be relocated to the Springfield United Methodist Church, 7047 Old Keene Mill Rd, Springfield, VA 22150.',
    latitude: 38.7783912,
    longitude: -77.1873566,
    active: true,
    provenance: {
      state: 'needs-review',
      source: 'sluglines.com WordPress export (legacy site; its own content predates 2020)',
    },
    peakHours: '5:45 AM – 8:00 AM',
    parking: 'There are about 685 parking spaces, it gets full by 7:00 AM. At the shopping complex and American Legion, commuter parking spaces are marked in blue. 254 spaces Springfield plaza, 7206 Old Keene Mill Rd, Springfield, VA 22150 ( http://www.myspringfieldplaza.com ). 100 spaces American Legion, 6500 Amherst Avenue, Springfield, VA 22150. 53 spaces 7047 Old Keene Mill Rd, Springfield, VA 22150 ( http://www.sumc-cares.org ). 278 spaces former Circuit City lot, 7039 Old Keene Mill Road, Springfield, VA 22150.',
    linesFrom: ['L’Enfant Plaza', '14th at Commerce Dept.', '18th Street'],
    linesTo: ['L’Enfant Plaza', '14th at Commerce Dept.', '14th & Madison Dr', '19th & F Street'],
    fbUrl: 'https://www.facebook.com/groups/springfieldsluglines/',
    image: {
      src: '/spots/Bobs.jpg',
      width: 460,
      height: 344,
      alt: 'Transit diagram for Bob\'s - Old Keene Mill Rd, republished from the legacy sluglines.com page for this spot.',
      sourceUrl: 'https://sluglines.com/images/slugging_locations/Bobs.jpg',
      fetchedAt: '2026-08-22',
    },
  },
  {
    slug: 'cardinal-forest-plaza',
    routeSlug: 'cardinal-forest-plaza',
    name: 'Cardinal Forest Plaza',
    corridor: 'I-395 / I-95',
    direction: 'Morning',
    county: 'Fairfax',
    destination: 'Pentagon, L\'Enfant Plaza, and 14th Street',
    description: 'Cardinal Forest aka Rolling Road sluglines form next to the Shell station (https://goo.gl/maps/apZGwkefh6x) on Old Keene Mill Road across the Cardinal Forest Shopping complex. Slugs park their vehicle in front of the shopping complex and cross the road to lineup near the bus stop for Pentagon.',
    linesTo: ['14th Street and Constitution Ave', 'L’Enfant Plaza', 'The Pentagon', '19th & F St', '15th Street & New York Ave'],
    parking: '100 Spaces near TD Bank (https://goo.gl/maps/KegSdkmzXi92).',
    latitude: 38.7794583,
    longitude: -77.2314818,
    active: true,
    provenance: {
      state: 'needs-review',
      source: 'sluglines.com WordPress export (legacy site; its own content predates 2020)',
    },
    peakHours: '6:30 AM – 8:00 AM',
    linesFrom: ['The Pentagon'],
  },
  {
    slug: 'franconia-springfield',
    routeSlug: 'Franconia-Springfield',
    name: 'Franconia - Springfield',
    corridor: 'I-395 / I-95',
    direction: 'Morning',
    county: 'Fairfax',
    destination: 'Pentagon, downtown DC, and Northern Virginia commuter destinations',
    description: 'Franconia-Springfield is a major transit hub, with both rail and bus service. WMATA metro rail services operate all day and Virginia Railway Express operates during peak hours. There are several bus services operated by WMATA, Fairfax connector, PRTC, and Greyhound.',
    parking: '5,069 spaces.',
    peakHours: '07:00 AM – 08:00 AM',
    latitude: 38.767306,
    longitude: -77.168972,
    active: false,
    provenance: {
      state: 'needs-review',
      source: 'sluglines.com WordPress export (legacy site; its own content predates 2020)',
    },
  },
  {
    slug: 'lorton',
    routeSlug: 'Lorton',
    name: 'Lorton',
    corridor: 'I-395 / I-95',
    direction: 'Morning',
    county: 'Fairfax',
    destination: 'Pentagon, downtown DC, and Northern Virginia commuter destinations',
    description: 'Riders line up in front of the VRE station at the parking lot. Most of the riders go to Pentagon and take a metro from there to their work location. There is a designated staging area for Lorton slugs at the Pentagon parking lot.',
    linesTo: ['The Pentagon'],
    linesFrom: ['The Pentagon'],
    parking: '567 Spaces VRE Lorton.',
    peakHours: '3:00 PM – 6:00 PM',
    latitude: 38.715012,
    longitude: -77.213593,
    active: false,
    provenance: {
      state: 'needs-review',
      source: 'sluglines.com WordPress export (legacy site; its own content predates 2020)',
    },
    image: {
      src: '/spots/Lorton.jpg',
      width: 460,
      height: 302,
      alt: 'Transit diagram for Lorton, republished from the legacy sluglines.com page for this spot.',
      sourceUrl: 'https://sluglines.com/images/slugging_locations/Lorton.jpg',
      fetchedAt: '2026-08-22',
    },
  },
  {
    slug: 'rolling-valley',
    routeSlug: 'Rolling-Valley',
    name: 'Rolling Valley',
    corridor: 'I-395 / I-95',
    direction: 'Morning',
    county: 'Fairfax',
    destination: 'Pentagon, L\'Enfant Plaza, and 14th Street',
    description: 'Rolling Valley is one of the biggest lot in Fairfax County with 664 parking spaces. This location is famous for slugging to the Pentagon and L’Enfant Plaza other destinations have lesser traffic.',
    linesTo: ['The Pentagon', 'Rosslyn', 'L’Enfant Plaza', '14th Street and Constitution Ave', '19th & F St'],
    parking: '664 spaces.',
    latitude: 38.7758648,
    longitude: -77.2629826,
    active: true,
    provenance: {
      state: 'needs-review',
      source: 'sluglines.com WordPress export (legacy site; its own content predates 2020)',
    },
    peakHours: '7:00 AM – 8:00 AM',
    linesFrom: ['The Pentagon', 'Rosslyn', 'Crystal City', 'L’Enfant Plaza', '14th Street', '18th / 20th / 23rd Street up to Pennsylvania Ave'],
    image: {
      src: '/spots/Rolling_Valley.jpg',
      width: 460,
      height: 341,
      alt: 'Transit diagram for Rolling Valley, republished from the legacy sluglines.com page for this spot.',
      sourceUrl: 'https://sluglines.com/images/slugging_locations/Rolling_Valley.jpg',
      fetchedAt: '2026-08-22',
    },
  },
  {
    slug: 'saratoga',
    routeSlug: 'Saratoga',
    name: 'Saratoga',
    corridor: 'I-395 / I-95',
    direction: 'Morning',
    county: 'Fairfax',
    destination: 'Pentagon, downtown DC, and Northern Virginia commuter destinations',
    description: 'Saratoga parking lot is right off the new section of the Fairfax County Parkway, provides an easy access to I-95. Slugs use this line along with Sydenstricker’s Rd and Rolling Valley as all the SlugStops destined to go to Pentagon.',
    linesTo: ['The Pentagon'],
    linesFrom: ['The Pentagon'],
    parking: '535 parking spaces.',
    peakHours: '6:00 AM – 8:00 AM',
    latitude: 38.7454983,
    longitude: -77.2100791,
    active: false,
    provenance: {
      state: 'needs-review',
      source: 'sluglines.com WordPress export (legacy site; its own content predates 2020)',
    },
    image: {
      src: '/spots/Saratoga.jpg',
      width: 460,
      height: 355,
      alt: 'Transit diagram for Saratoga, republished from the legacy sluglines.com page for this spot.',
      sourceUrl: 'https://sluglines.com/images/slugging_locations/Saratoga.jpg',
      fetchedAt: '2026-08-22',
    },
  },
  {
    slug: 'sydenstricker-rd',
    routeSlug: 'Sydenstricker-Rd',
    name: 'Sydenstricker Rd',
    corridor: 'I-395 / I-95',
    direction: 'Morning',
    county: 'Fairfax',
    destination: 'Pentagon, L\'Enfant Plaza, and 14th Street',
    description: 'The Sydenstricker primarily servers Pentagon drivers and riders, some drivers call for Crystal City or Rosslyn. All riders share the one line for all stops. Riders line up along the concrete sidewalk at the parking lot.',
    linesTo: ['The Pentagon', 'L’Enfant Plaza', '14th Street and Constitution Ave'],
    linesFrom: ['The Pentagon', 'Rosslyn'],
    parking: '170 Spaces Sydenstricker Road 8500 Hooes Road, Springfield, VA 22153.',
    latitude: 38.755989,
    longitude: -77.238098,
    active: true,
    provenance: {
      state: 'needs-review',
      source: 'sluglines.com WordPress export (legacy site; its own content predates 2020)',
    },
    peakHours: '5:45 A.M – 8:00 A.M',
    image: {
      src: '/spots/Sydenstricker.jpg',
      width: 460,
      height: 309,
      alt: 'Transit diagram for Sydenstricker Rd, republished from the legacy sluglines.com page for this spot.',
      sourceUrl: 'https://sluglines.com/images/slugging_locations/Sydenstricker.jpg',
      fetchedAt: '2026-08-22',
    },
  },
  {
    slug: 'springfield-town-center',
    routeSlug: 'springfield-town-center',
    name: 'Springfield Town Center',
    corridor: 'I-395 / I-95',
    direction: 'Morning',
    county: 'Fairfax',
    destination: 'L\'Enfant Plaza, 14th at Commerce Dept., and 18th Street',
    description: 'There are about 500 parking spaces leased by Fairfax County for commuters. County is leasing additional 300 spaces to accommodate Bobs slugs. There are no sluglines at this time, but commuters park at this garage and walk to the Franconia-Springfield Metro station, primarily because parking is free at this location. With the Clean Fuel tags that expired last month and the new I-395 Express Lanes that are opening on November 17th, 2019 this will be an option for commuters from East of I-95.',
    latitude: null,
    longitude: null,
    active: false,
    provenance: {
      state: 'needs-review',
      source: 'sluglines.com WordPress export (legacy site; its own content predates 2020)',
    },
    parking: '800 spaces.',
    linesFrom: ['L’Enfant Plaza', '14th at Commerce Dept.', '18th Street'],
    linesTo: ['L’Enfant Plaza', '14th at Commerce Dept.', '14th & Madison Dr', '19th & F Street'],
    fbUrl: 'https://www.facebook.com/groups/STCSluglines/',
    notes: 'Legacy-only: present in the /slug_pickup/ inventory, absent from the curated live directory. No coordinates on the legacy page.',
  },
  {
    slug: 'van-dorn-st',
    routeSlug: 'van-dorn-st',
    name: 'Van Dorn St',
    corridor: 'I-395 / I-95',
    direction: 'Morning',
    county: 'Fairfax / Alexandria',
    destination: 'L\'Enfant Plaza, 14th Street, and 18th Street',
    description: 'Van Dorn Metro park-and-ride. The legacy page title carries an explicit [Inactive] marker.',
    latitude: null,
    longitude: null,
    active: false,
    provenance: {
      state: 'needs-review',
      source: 'sluglines.com WordPress export (legacy site; its own content predates 2020)',
    },
    peakHours: '07:00 AM – 08:00 AM',
    parking: '361 spaces.',
    linesFrom: ['L\'Enfant Plaza', '14th Street', '18th Street'],
    linesTo: ['L\'Enfant Plaza', '14th & Madison Ave', '19th & F Street'],
    notes: 'Legacy-only: present in the /slug_pickup/ inventory, absent from the curated live directory. Marked [Inactive] on the legacy page. No coordinates on the legacy page.',
  },
  {
    slug: 'landmark-mall',
    routeSlug: 'landmark-mall',
    name: 'Landmark Mall',
    corridor: 'I-395 / I-95',
    direction: 'Morning',
    county: 'Fairfax / Alexandria',
    destination: 'L\'Enfant Plaza, 14th Street, and 18th Street',
    description: 'Bus stop #4000576 on the Landmark Mall roadway. The legacy page title carries an explicit [Inactive] marker.',
    latitude: null,
    longitude: null,
    active: false,
    provenance: {
      state: 'needs-review',
      source: 'sluglines.com WordPress export (legacy site; its own content predates 2020)',
    },
    peakHours: '07:00 AM – 08:00 AM',
    parking: 'Parking available next to bus stop #4000576 (Landmark Mall Rdwy & Mall Entrance) on the lower level of the parking garage in rows K, L, M, N, and O. Parking permits are required and can be obtained by emailing goalex@alexandriava.gov. Parking is limited and available on a first-come, first-serve basis.',
    linesFrom: ['L\'Enfant Plaza', '14th Street', '18th Street'],
    fbUrl: 'https://www.facebook.com/groups/dcsluglines/',
    notes: 'Legacy-only: present in the /slug_pickup/ inventory, absent from the curated live directory. Marked [Inactive] on the legacy page. No coordinates on the legacy page.',
  },
  {
    slug: 'route-3-gordon-rd',
    routeSlug: 'Route-3-Gordon-Rd',
    name: 'Route 3 - Gordon Rd',
    corridor: 'I-395 / I-95',
    direction: 'Morning',
    county: 'Stafford / Fredericksburg',
    destination: 'Pentagon, L\'Enfant Plaza, and 14th Street',
    description: 'The Gordon road commuter lot is located at the intersection of Route 3 and Gordon road in Spotsylvania County. It is approximately 3 miles west of I-95 (exit 130). There are few commuters going to Quantico, Tysons and Alexandria, having a sign will help get a direct ride to your destination. Consider joining Rt. 3 Facebook Group to coordinate rides.',
    linesTo: ['The Pentagon', 'Rosslyn'],
    linesFrom: ['The Pentagon', 'Rosslyn [ Inactive ]', 'Quantico [ Inactive ]', 'Crystal City [ Inactive ]'],
    parking: '1,052 parking spaces.',
    latitude: 38.2895891,
    longitude: -77.5634542,
    active: true,
    provenance: {
      state: 'needs-review',
      source: 'sluglines.com WordPress export (legacy site; its own content predates 2020)',
    },
    peakHours: '5:30 AM – 6:30 AM',
  },
  {
    slug: 'route-17',
    routeSlug: 'Route-17',
    name: 'Route 17',
    corridor: 'I-395 / I-95',
    direction: 'Morning',
    county: 'Stafford / Fredericksburg',
    destination: 'Pentagon, L\'Enfant Plaza, and 14th Street',
    description: 'The Rt. 17 lot is an early lot, commuters leave the lot before 7 AM. Commuters can get to Pentagon, L’Enfant or 14th street. Drivers and riders are encouraged to display signs for their destinations such as Rosslyn and Crystal City.',
    linesTo: ['The Pentagon', 'Rosslyn', 'Crystal City 23rd Street'],
    linesFrom: ['L’Enfant Plaza', '14th St at Commerce Dept.', 'The Pentagon', 'Rosslyn', 'Crystal City 23rd Street'],
    parking: 'The new lot will have a total of 1,865 parking spaces.',
    latitude: 38.3461443,
    longitude: -77.5018604,
    active: true,
    provenance: {
      state: 'needs-review',
      source: 'sluglines.com WordPress export (legacy site; its own content predates 2020)',
    },
    peakHours: '5:30 A.M – 8:30 A.M',
  },
  {
    slug: 'route-208',
    routeSlug: 'Route-208',
    name: 'Route 208',
    corridor: 'I-395 / I-95',
    direction: 'Morning',
    county: 'Stafford / Fredericksburg',
    destination: 'Pentagon, downtown DC, and Northern Virginia commuter destinations',
    description: 'Take I-95 to Exit 126A. The morning slugs depart Fredericksburg from Route 208 SlugStop, and terminates at the Pentagon in about 1 hour and 25 minutes. Business Route 208 is heavily impacted by traffic as it becomes a route to several Spotsylvania county’s department. So sluggers need to be alert on traffic signs of incoming drivers.',
    linesFrom: ['14th St at Commerce Dept.', 'Crystal City 23rd Street', 'The Pentagon', 'Rosslyn'],
    parking: '805 Free Parking Spaces in Spotsylvania County, located on Houser Drive Off Route 208.',
    peakHours: '5:00 A.M – 6:30 A.M',
    latitude: 38.25132,
    longitude: -77.508324,
    active: false,
    provenance: {
      state: 'needs-review',
      source: 'sluglines.com WordPress export (legacy site; its own content predates 2020)',
    },
  },
  {
    slug: 'dale-city',
    routeSlug: 'Dale-City',
    name: 'Dale City',
    corridor: 'I-395 / I-95',
    direction: 'Morning',
    county: 'Prince William',
    destination: 'Pentagon, downtown DC, and Northern Virginia commuter destinations',
    description: 'The Dale City Park and Ride is located at the intersection of Dale Blvd. and Gemini Way in Dale City, VA hidden behind Gaint Food. The lot is along the Gemini Way accessible from Dale Blvd. or Minnieville Road. Slugs from one line for both Pentagon and Rosslyn and the lot always has space for parking. Slugging picked up from this lot after Potomac Mills reduced commuter parking space, but as there is no return lines from Pentagon most of the slugs get a ride to Horner or Potamac Mills and take a bus from there to Dale City parking lot.',
    linesFrom: ['Crystal City', 'Rosslyn', 'The Pentagon'],
    parking: '591 Spaces.',
    peakHours: '6:30 AM – 7:30 AM',
    latitude: 38.646938,
    longitude: -77.341232,
    active: false,
    provenance: {
      state: 'needs-review',
      source: 'sluglines.com WordPress export (legacy site; its own content predates 2020)',
    },
  },
  {
    slug: 'horner-rd',
    routeSlug: 'Horner-Rd',
    name: 'Horner Rd',
    corridor: 'I-395 / I-95',
    direction: 'Morning',
    county: 'Prince William',
    destination: 'Pentagon, L\'Enfant Plaza, and 14th Street',
    description: 'The Horner Road Commuter Parking Lot is situated to west of I-95 and north of Prince William Parkway, a free parking lot, maintained by VDoT. It is one of the largest parking lots in Prince William County having about 3100 parking spaces, but still fills up by about 7.30 AM. This is a very popular lot for slugging and has a ride back for almost all destinations. Due to its popularity and demand, VDoT and Prince William County added another 600 parking spaces in 2015. This lot has direct access to the I-95 HOT lanes.',
    linesTo: ['L’Enfant Plaza', 'Navy Yard', '14th St at Commerce Dept.', '15th Street & New York Ave', '19th & I Street', 'The Pentagon', 'Mark Center', 'Rosslyn', 'Crystal City 12th Street', 'Crystal City 23rd Street'],
    parking: '2363 spaces in the old lot on the east of Telegraph Road. 600 spaces in the new lot on west of Telegraph Road.',
    latitude: 38.658592,
    longitude: -77.280746,
    active: true,
    provenance: {
      state: 'needs-review',
      source: 'sluglines.com WordPress export (legacy site; its own content predates 2020)',
    },
    peakHours: '5:30 A.M – 7:00 A.M',
    linesFrom: ['14th Street', '18th Street', 'Crystal City', 'L’Enfant Plaza and Navy Yard', 'Mark Center', 'Rosslyn', 'The Pentagon'],
  },
  {
    slug: 'montclair-fire-station',
    routeSlug: 'Montclair-Fire-Station',
    name: 'Montclair Fire Station',
    corridor: 'I-395 / I-95',
    direction: 'Morning',
    county: 'Prince William',
    destination: 'Pentagon, L\'Enfant Plaza, and 14th Street',
    description: 'Montclair Fire Station is also know as Montclair / Dumfries parking lot. Parking is Limited along Spring branch Boulevard. To avoid heavier traffic in water way drive proceeding north along Spring branch boulevard.',
    linesTo: ['The Pentagon'],
    linesFrom: ['The Pentagon'],
    parking: '52 Spaces.',
    latitude: 38.62624,
    longitude: -77.348183,
    active: true,
    provenance: {
      state: 'needs-review',
      source: 'sluglines.com WordPress export (legacy site; its own content predates 2020)',
    },
    peakHours: '6:00 AM – 6:30 AM',
    fbUrl: 'https://www.facebook.com/groups/montclairslugs/',
  },
  {
    slug: 'montclair-northgate',
    routeSlug: 'Montclair-Northgate',
    name: 'Montclair Northgate',
    corridor: 'I-395 / I-95',
    direction: 'Morning',
    county: 'Prince William',
    destination: 'Pentagon, L\'Enfant Plaza, and 14th Street',
    description: 'Parking is along the north-gate and eastern side of waterway drive. An alternative route has been planned for growing ridership to Downtown D.C area for the buses that stop at pentagon. Once it is completed the Montclair community will have two routes separately for Downtown Washington and pentagon. It provides an effective alternative mode for sluggers as this changing bus routes provides morning and evening buses.',
    linesTo: ['15th Street & New York Ave', 'The Pentagon'],
    linesFrom: ['The Pentagon'],
    parking: '52 Spaces.',
    latitude: 38.6105087,
    longitude: -77.359309,
    active: true,
    provenance: {
      state: 'needs-review',
      source: 'sluglines.com WordPress export (legacy site; its own content predates 2020)',
    },
    peakHours: '5:30 A.M – 6:30 A.M',
    fbUrl: 'https://www.facebook.com/groups/montclairslugs/',
  },
  {
    slug: 'old-hechingers',
    routeSlug: 'Old-Hechingers',
    name: 'Old Hechingers',
    corridor: 'I-395 / I-95',
    direction: 'Morning',
    county: 'Prince William',
    destination: 'Pentagon, L\'Enfant Plaza, and 14th Street',
    description: 'The parking has a parking capacity of 580 spaces with three entry/exit points from Old Bridge Road, Route 123 and Devils Reach Road. Riders line up at the bus stop in the parking lot and drivers pull up in the bus lane to pick up riders. Old Hechinger Commuter lot was named after the old home improvement chain store Hechinger Company that was closed in 1999. The store at this location was demolished to add about 250 parking spaces to the existing 400 spaces.',
    linesTo: ['Pentagon', '14th Street and Constitution Ave', '15th Street & New York Ave'],
    linesFrom: ['14th St at Commerce Dept. and 18th Street'],
    parking: '580 spaces,. 1310 Old Bridge Road,. Woodbridge, VA 22192.',
    latitude: 38.674301,
    longitude: -77.255623,
    active: true,
    provenance: {
      state: 'needs-review',
      source: 'sluglines.com WordPress export (legacy site; its own content predates 2020)',
    },
    peakHours: '7:00 -8:00 A.M',
  },
  {
    slug: 'potomac-mills',
    routeSlug: 'Potomac-Mills',
    name: 'Potomac Mills',
    corridor: 'I-395 / I-95',
    direction: 'Morning',
    county: 'Prince William',
    destination: 'Pentagon, Crystal City, Rosslyn, and DC',
    description: 'Potomac Mills mall parking has been reduced from 1000 spaces to 275 to reduce the congestion at customer parking at the Potomac Mills Mall. With limited parking space, not many people slug from this lot.',
    linesFrom: ['18th Street'],
    latitude: 38.640717,
    longitude: -77.293884,
    active: true,
    provenance: {
      state: 'needs-review',
      source: 'sluglines.com WordPress export (legacy site; its own content predates 2020)',
    },
    peakHours: '6:30 AM – 8:15 AM',
    parking: '275 Parking Spaces around Potomac Mills Circle, commuters are allowed to park only in the parking spots that are marked in yellow.',
    linesTo: ['The Pentagon', '15th Street & New York Ave', 'Rosslyn'],
    fbUrl: 'https://www.facebook.com/groups/potomacmillssluglines/',
  },
  {
    slug: 'route-123',
    routeSlug: 'Route-123',
    name: 'Route 123',
    corridor: 'I-395 / I-95',
    direction: 'Morning',
    county: 'Prince William',
    destination: 'Pentagon, L\'Enfant Plaza, and 14th Street',
    description: 'Slug line from Route 123 is not an established line, drivers going to Tysons swing to pickup bus riders going to Tysons. There is no return lines from Tysons to Route 123. The lot is easily accessible from Gordon Blvd and exit 160 of I-95.',
    linesFrom: ['The Pentagon', 'Tysons Corner'],
    parking: '770 Spaces along the intersection of Route 123 & I-95.',
    latitude: 38.6701716,
    longitude: -77.2509748,
    active: true,
    provenance: {
      state: 'needs-review',
      source: 'sluglines.com WordPress export (legacy site; its own content predates 2020)',
    },
    peakHours: 'Peak rides: 6:20 AM – 8:15 AM',
  },
  {
    slug: 'route-234',
    routeSlug: 'Route-234',
    name: 'Route 234',
    corridor: 'I-395 / I-95',
    direction: 'Morning',
    county: 'Prince William',
    destination: 'Pentagon, L\'Enfant Plaza, and 14th Street',
    description: 'The Parking lot has its easy access to US 1 express highway lanes (Jefferson Davis Highway)and Exit 152 So it is highly competitive for drivers to find parking as the commuters come from Dumfries, Triangle, Stafford, and even Fredericksburg.',
    linesFrom: ['14th Street and L’Enfant Plaza', 'Crystal City', 'Rosslyn', 'The Pentagon', '18th Street'],
    parking: 'The increase in capacity by 400 spaces makes total of 830 Parking Spaces along US 1 (Jefferson Davis Highway) at Route 234 (Dumfries Road).',
    latitude: 38.576817,
    longitude: -77.315826,
    active: true,
    provenance: {
      state: 'needs-review',
      source: 'sluglines.com WordPress export (legacy site; its own content predates 2020)',
    },
    peakHours: '6:00 AM – 7:00 AM',
  },
  {
    slug: 'tacketts-mill',
    routeSlug: 'Tacketts-Mill',
    name: 'Tacketts Mill',
    corridor: 'I-395 / I-95',
    direction: 'Morning',
    county: 'Prince William',
    destination: 'Pentagon, L\'Enfant Plaza, and 14th Street',
    description: 'The Tackett’s Mill Commuter lot is at the intersection of Minnieville Road and Old Bridge Road. Riders lineup in two locations, one going to the Pentagon and other goes to Rosslyn and Crystal City. There is also a overflow parking lot across this lot in the shopping complex, but make sure to park only in the commuter parking spaces.',
    linesTo: ['The Pentagon', 'Crystal City', 'Rosslyn'],
    linesFrom: ['Crystal City and Rosslyn', 'The Pentagon'],
    parking: 'Tackett’s Mill Commuter lot has about 530 Spaces. Overflow parking is across the lot in the shopping complex or called McDonald’s lot with 120 spaces.',
    latitude: 38.675777,
    longitude: -77.276543,
    active: true,
    provenance: {
      state: 'needs-review',
      source: 'sluglines.com WordPress export (legacy site; its own content predates 2020)',
    },
    peakHours: '7:00 AM – 8:30 AM',
  },
  {
    slug: 'telegraph-rd',
    routeSlug: 'Telegraph-Rd',
    name: 'Telegraph Rd',
    corridor: 'I-395 / I-95',
    direction: 'Morning',
    county: 'Prince William',
    destination: 'Pentagon, L\'Enfant Plaza, and 14th Street',
    description: 'The Telegraph Rd. Commuter Lot is on the Telegraph Road, next to the Sheets Gas Station. Lot can be accessed both from the Caton Hill Road and Telegraph Road. Slugging provides a great opportunity for growing ridership, as there is lack of commuter parking in Horner Road Commuter Lot.',
    linesTo: ['L’Enfant Plaza', '14th St at Commerce Dept.', '15th Street & New York Ave', '19th & I St', 'Crystal City 23rd St', 'Crystal City 12th St', 'Navy Yard', 'The Pentagon', 'Rosslyn', 'Mark Center'],
    linesFrom: ['14th Street', '18th Street', 'Crystal City', 'L’Enfant Plaza and Navy Yard', 'Rosslyn', 'The Pentagon', 'Mark Center'],
    parking: '600 Free parking Spaces.',
    latitude: 38.658051,
    longitude: -77.288749,
    active: true,
    provenance: {
      state: 'needs-review',
      source: 'sluglines.com WordPress export (legacy site; its own content predates 2020)',
    },
    peakHours: '7:00 AM – 8:15 AM',
  },
  {
    slug: 'route-610-mine-rd',
    routeSlug: 'Route-610-Mine-Rd',
    name: 'Route 610 - Mine Rd',
    corridor: 'I-395 / I-95',
    direction: 'Morning',
    county: 'Stafford / Fredericksburg',
    destination: 'Pentagon and L\'Enfant Plaza',
    description: 'The Mine Road lot with 750 parking spaces is on the south of Rt. 610 Garrisonville Road. This parking lot fills up early, alternate parking space is on the Staffordboro Blvd. not or Rt. 610. There are two lines one going to Arlington and the other to DC destinations.',
    linesTo: ['L’Enfant Plaza', 'The Pentagon', 'Rosslyn', 'Crystal City', '14th and G Street', '14th and Independence Ave (New)'],
    linesFrom: ['L’Enfant Plaza', 'Navy Yard', '14th & G Street', '18th Street', 'The Pentagon', 'Crystal City'],
    parking: '750 spaces. Alternate parking at Staffordboro Parking Lot.',
    latitude: 38.4669945,
    longitude: -77.4160618,
    active: true,
    provenance: {
      state: 'needs-review',
      source: 'sluglines.com WordPress export (legacy site; its own content predates 2020)',
    },
    peakHours: '5:30 AM – 6:30 AM (Slugs line up as early as 4:30 AM)',
  },
  {
    slug: 'route-610-staffordboro-blvd',
    routeSlug: 'Route-610-Staffordboro-Blvd',
    name: 'Route 610 - Staffordboro Blvd',
    corridor: 'I-395 / I-95',
    direction: 'Morning',
    county: 'Stafford / Fredericksburg',
    destination: 'Pentagon and L\'Enfant Plaza',
    description: 'The Staffordboro Blvd Park & Ride lot in Garrisonville was opened on October 2014, with 1,865 parking spaces. This is one of the few lots that has Slug pickup areas, that can accommodate about 30 people to line up and 4 ideal cars. Riders going to the Pentagon, Rosslyn, Crystal City and DC locations form a single line. Commuters also discuss commuting challenges in the Facebook Group https://www.facebook.com/groups/StaffordSluglines/.',
    linesTo: ['The Pentagon', 'Rosslyn', 'Crystal City 12th and 23rd', 'L’Enfant Plaza', '14th and G Street', '14th and Independence Ave'],
    linesFrom: ['The Pentagon', 'Rosslyn', 'Crystal CIty', 'L’Enfant Plaza'],
    parking: '1,865 parking spaces.',
    latitude: 38.4752647,
    longitude: -77.4129771,
    active: true,
    provenance: {
      state: 'needs-review',
      source: 'sluglines.com WordPress export (legacy site; its own content predates 2020)',
    },
    peakHours: '5:00 AM – 7:30 AM',
  },
  {
    slug: 'route-630',
    routeSlug: 'Route-630',
    name: 'Route 630',
    corridor: 'I-395 / I-95',
    direction: 'Morning',
    county: 'Stafford / Fredericksburg',
    destination: 'Pentagon and L\'Enfant Plaza',
    description: 'Sluglines is located near the bus shelter. The traffic is eased by the VDOT reconstruction of lanes at the intersection between Route 630 (Courthouse Road) and I-95 Interchange.',
    linesTo: ['The Pentagon'],
    linesFrom: ['The Pentagon', 'Rosslyn', 'Crystal City'],
    parking: 'The 539 reduced space parking facility is located off Route 630 just west of I-95.',
    latitude: 38.4212359,
    longitude: -77.4254927,
    active: true,
    provenance: {
      state: 'needs-review',
      source: 'sluglines.com WordPress export (legacy site; its own content predates 2020)',
    },
    peakHours: '5:30 AM – 6:30 AM',
  },
  {
    slug: 'mark-center',
    routeSlug: 'Mark-Center',
    name: 'Mark Center',
    corridor: 'I-395 / I-95',
    direction: 'Afternoon',
    county: 'Fairfax / Alexandria',
    destination: 'Springfield, Lorton, and Fairfax-area lines',
    description: 'The Mark Center is a federal building opened in 2012 for DoD agencies. The Mark Center provides a designated staging area for slugging at the entrance of North Parking Garage on Mark Center Drive. Currently slugging is mostly coordinated by three different mailing lists to different locations. Mailing list is not open to public, commuters have to be a DoD personnel to access enroll to this mailing list others join the Mark Center Sluglines Facebook Group. Horner/Tacketts Mills: whs.mc-alex.hrd.list.sluggers-horner-tacketts@mail.mil. Route 234: whs.mc-alex.hrd.list.sluggers-montclair-234@mail.mil. Stafford/Fredericksburg: whs.mc-alex.hrd.list.sluggers-stafford-fredericksburg@mail.mil. There are no morning slug lines going to the Mark Center, commuters line up with the Pentagon lines and circle back to the Mark Center via Metrobus (Free for commuters with CAC). Some commuters coordinate rides.',
    linesFrom: ['Horner Rd', 'Route 234', 'Tacketts Mill [ Inactive ]', 'Telegraph Rd', 'Route 610 – Staffordboro Blvd'],
    latitude: 38.8310454,
    longitude: -77.1176246,
    active: true,
    provenance: {
      state: 'needs-review',
      source: 'sluglines.com WordPress export (legacy site; its own content predates 2020)',
    },
    peakHours: '4:00 PM – 5:00 PM',
    fbUrl: 'https://www.facebook.com/groups/markcenterslugs/',
  },
  {
    slug: 'tysons-corner',
    routeSlug: 'Tysons-Corner',
    name: 'Tysons Corner',
    corridor: 'I-395 / I-95',
    direction: 'Afternoon',
    county: 'Fairfax / Alexandria',
    destination: 'Fairfax and Springfield-area lines',
    description: 'Tysons Corner slug pickup is located at the bus stop on Jones Branch Dr. between Lincoln Way & Lincoln Center Ct. ahead of Fountains at McLean, 1503 Lincoln Center Ct. McLean, VA 22102.',
    linesFrom: ['Route 123'],
    latitude: 38.931906,
    longitude: -77.230132,
    active: true,
    provenance: {
      state: 'needs-review',
      source: 'sluglines.com WordPress export (legacy site; its own content predates 2020)',
    },
    peakHours: '3:30 PM - 6:30 PM',
  },
  {
    slug: 'crystal-city-12th-st',
    routeSlug: 'Crystal-City-12th-St',
    name: 'Crystal City 12th St',
    corridor: 'I-395 / I-95',
    direction: 'Afternoon',
    county: 'Arlington',
    destination: 'Fairfax, Prince William, and Stafford',
    description: 'The line forms at the northern end of Crystal City near the sharp turn on Crystal Drive and 12th Street 1272 Crystal Dr, Arlington, VA 22202 ( https://goo.gl/maps/SVHcnBKvozM2 ). Drivers heading north on Crystal Drive pick up slugs for Woodbridge Lines ( Horner Road and Tacketts Mill) near the bus stop and Stafford Lines (Route 610) in front of the park sign.',
    linesFrom: ['Route 610 (Stafford)', 'Horner Rd', 'Tacketts Mill', 'Telegraph Rd'],
    latitude: 38.8620732,
    longitude: -77.048738,
    active: true,
    provenance: {
      state: 'needs-review',
      source: 'sluglines.com WordPress export (legacy site; its own content predates 2020)',
    },
    peakHours: '4:00 PM – 5:00 PM',
    fbUrl: 'https://www.facebook.com/groups/crystalcitysluglines/',
    image: {
      src: '/spots/Crystal_City_12th_St.jpg',
      width: 460,
      height: 421,
      alt: 'Transit diagram for Crystal City 12th St, republished from the legacy sluglines.com page for this spot.',
      sourceUrl: 'https://sluglines.com/images/slugging_locations/Crystal_City_12th_St.jpg',
      fetchedAt: '2026-08-22',
    },
  },
  {
    slug: 'crystal-city-23rd-st',
    routeSlug: 'Crystal-City-23rd-St',
    name: 'Crystal City 23rd St',
    corridor: 'I-395 / I-95',
    direction: 'Afternoon',
    county: 'Arlington',
    destination: 'Fairfax, Prince William, and Stafford',
    description: 'Sluglines form along the Crystal Drive near the Bright Horizons day care at 2451 Crystal Dr, Arlington, VA 22202 ( https://goo.gl/maps/pce3ibvok462 ). Drivers heading north on Crystal Drive pick up slugs for Horner Road and Tacketts Mill just before the cross walk light and Route 610 slugs past this cross walk.',
    linesFrom: ['Route 610 (Stafford)', 'Horner Rd', 'Tacketts Mill', 'Telegraph Rd'],
    latitude: 38.85238,
    longitude: -77.04964,
    active: true,
    provenance: {
      state: 'needs-review',
      source: 'sluglines.com WordPress export (legacy site; its own content predates 2020)',
    },
    peakHours: '4:00 PM – 5:00 PM',
    fbUrl: 'https://www.facebook.com/groups/crystalcitysluglines/',
    image: {
      src: '/spots/Crystal_City_12th_St.jpg',
      width: 460,
      height: 421,
      alt: 'Transit diagram for Crystal City 23rd St, republished from the legacy sluglines.com page for this spot.',
      sourceUrl: 'https://sluglines.com/images/slugging_locations/Crystal_City_12th_St.jpg',
      fetchedAt: '2026-08-22',
    },
  },
  {
    slug: 'rosslyn',
    routeSlug: 'Rosslyn',
    name: 'Rosslyn',
    corridor: 'I-395 / I-95',
    direction: 'Afternoon',
    county: 'Arlington',
    destination: 'Northern Virginia corridors',
    description: 'In 2002, Arlington county placed signs for sluglines staging area at this location for Springfield, Woodbridge and Frediricksburg Commuters. Sluglines to Bobs / Springfield forms in the corner for N.Kent Street and Wilson Blvd. Riders line up on the N. Kent Street, the nearest address is 1601, North Kent Street, Arlington, VA – 22209. Sluglines to Tacketts, Horner, Potomac and Stafford forms between North Moore Street and North Fort Myer Drive on the Lee Highway service road.',
    linesFrom: ['North Kent Street', 'Bobs (Old Keene Mill Rd)', 'Rolling Valley', 'Lee Highway service road', 'Horner Rd', 'Potomac Mills [ Inactive ]', 'Old Hechingers [ Inactive ]', 'Stafford'],
    latitude: 38.898092,
    longitude: -77.071726,
    active: true,
    provenance: {
      state: 'needs-review',
      source: 'sluglines.com WordPress export (legacy site; its own content predates 2020)',
    },
    peakHours: '3:15 PM – 6:00 PM',
    fbUrl: 'https://www.facebook.com/groups/rosslynsluglines/',
  },
  {
    slug: 'the-pentagon',
    routeSlug: 'The-Pentagon',
    name: 'The Pentagon',
    corridor: 'I-395 / I-95',
    direction: 'Afternoon',
    county: 'Arlington',
    destination: 'All Northern Virginia corridors',
    description: 'Sluglines was started in the mid 1970’s between the Pentagon and the Bob’s at Springfield. Since then it had been growing and today we have about 5000 commuters slug from the Pentagon to different locations along I-95 corridor. The I-66 tolls inside beltway that started on December 4, 2017, drivers are looking to pick up riders from the Pentagon. The new off ramp from the north bound I-395 Express Lanes to the Pentagon South Parking lot that was opened on November 17th 2019 has significantly reduced the morning backups on the old HOV-3 lanes.',
    latitude: 38.8680768,
    longitude: -77.0524506,
    active: true,
    provenance: {
      state: 'needs-review',
      source: 'sluglines.com WordPress export (legacy site; its own content predates 2020)',
    },
    peakHours: '3:00 PM – 6:00 PM',
    fbUrl: 'https://www.facebook.com/groups/pentagonsluglines/',
  },
  {
    slug: '14th-st-and-constitution-ave',
    routeSlug: '14th-St-and-Constitution-Ave',
    name: '14th St and Constitution Ave',
    corridor: 'I-395 / I-95',
    direction: 'Afternoon',
    county: 'Washington DC',
    destination: 'Northern Virginia commuter lots',
    description: 'The 14th and Constitution slug pick up location that serves Springfield commuters has been moved to 14th and Madison. Riders heading to Bob’s and Rolling Valley line up here in single file at this location. The driver has to call out their drop off location, to pickup riders. It is challenging for drivers to pull up and pick up riders when food trucks parked taking the right lane. Drivers, when you are stopping on the second left lane to pick up riders, it is not safe and traffic officers may ticket you.',
    linesFrom: ['Bobs – Old Keene Mill Rd', 'Rolling Valley'],
    peakHours: '3:30 PM – 6:00 PM',
    latitude: 38.889938,
    longitude: -77.032021,
    active: true,
    provenance: {
      state: 'needs-review',
      source: 'sluglines.com WordPress export (legacy site; its own content predates 2020)',
    },
  },
  {
    slug: '14th-st-and-g-st',
    routeSlug: '14th-St-and-G-St',
    name: '14th St and G St',
    corridor: 'I-395 / I-95',
    direction: 'Afternoon',
    county: 'Washington DC',
    destination: 'Northern Virginia commuter lots',
    description: '14th St and G St is a afternoon slug line location in Washington DC serving the I-395 / I-95 corridor.',
    linesFrom: ['Route 610'],
    peakHours: '3:30 PM – 5:00 PM',
    latitude: 38.8981415,
    longitude: -77.0320751,
    active: true,
    provenance: {
      state: 'needs-review',
      source: 'sluglines.com WordPress export (legacy site; its own content predates 2020)',
    },
  },
  {
    slug: '14th-st-and-independence',
    routeSlug: '14th-St-and-Independence',
    name: '14th St and Independence',
    corridor: 'I-395 / I-95',
    direction: 'Afternoon',
    county: 'Washington DC',
    destination: 'Northern Virginia commuter lots',
    description: 'Due to excess congestion of this slugline between parking buses and slugging cars, carpooling has been shifted to new area. The slugline is relocated to north of intersection near the railing on auditors building. The sluggers can access both bus and car at this stop.',
    linesFrom: ['Potomac Mills', 'Horner Rd', 'Route 234', 'Telegraph Rd', 'Old Hechingers'],
    peakHours: '3:00 PM – 5:30 PM',
    latitude: 38.88733,
    longitude: -77.032156,
    active: true,
    provenance: {
      state: 'needs-review',
      source: 'sluglines.com WordPress export (legacy site; its own content predates 2020)',
    },
  },
  {
    slug: '14th-st-at-commerce-dept',
    routeSlug: '14th-St-at-Commerce-Dept',
    name: '14th St at Commerce Dept.',
    corridor: 'I-395 / I-95',
    direction: 'Afternoon',
    county: 'Washington DC',
    destination: 'Northern Virginia commuter lots',
    description: 'The sluglines are co-located with the bus stop on the 14th Street in front of the Commerce building, between Pennsylvania Ave NW and Constitution Ave NW. Due to the construction slugs move between between Pennsylvania Ave NW and Constitution Ave NW.',
    linesFrom: ['Horner Rd', 'Potomac Mills', 'Old Hechingers', 'Telegraph Rd', 'Tacketts Mill'],
    peakHours: '4:00 PM – 5:00 PM',
    latitude: 38.89462,
    longitude: -77.03207,
    active: true,
    provenance: {
      state: 'needs-review',
      source: 'sluglines.com WordPress export (legacy site; its own content predates 2020)',
    },
    image: {
      src: '/spots/14th_St_at_Commerce_Dept.jpg',
      width: 460,
      height: 396,
      alt: 'Transit diagram for 14th St at Commerce Dept., republished from the legacy sluglines.com page for this spot.',
      sourceUrl: 'https://sluglines.com/images/slugging_locations/14th_St_at_Commerce_Dept.jpg',
      fetchedAt: '2026-08-22',
    },
  },
  {
    slug: '15th-st-and-new-york-ave',
    routeSlug: '15th-St-and-New-York-Ave',
    name: '15th St and New York Ave',
    corridor: 'I-395 / I-95',
    direction: 'Afternoon',
    county: 'Washington DC',
    destination: 'Northern Virginia commuter lots',
    description: 'Riders line up along NY Ave NW near the 15th St. Cars have enough space to pull up and wait as the street side parking is not allowed after 3.00 PM. It is convenient riders to hope on the PRTC bus stops.',
    linesFrom: ['Horner Rd', 'Potomac Mills', 'Old Hechingers', 'Tacketts Mill', 'Telegraph Rd', 'Vienna Metro South KnR', 'Fairfax Govt', 'Stringfellow PnR', 'Herndon-Monroe PnR', 'Cushing Road'],
    peakHours: '3:00 P.M – 6:00 P.M',
    latitude: 38.8990078,
    longitude: -77.033381,
    active: true,
    provenance: {
      state: 'needs-review',
      source: 'sluglines.com WordPress export (legacy site; its own content predates 2020)',
    },
  },
  {
    slug: '19th-st-and-f-st',
    routeSlug: '19th-St-and-F-St',
    name: '19th St and F St',
    corridor: 'I-395 / I-95',
    direction: 'Afternoon',
    county: 'Washington DC',
    destination: 'Northern Virginia commuter lots',
    description: 'Line forms on 19th street between F and E street in front of The George Washington University – Mitchell Hall entrance. This is one of the old and popular lines that was moved from 18th and F street to 19th and F.',
    linesFrom: ['Bobs (Old Keene Mill Rd)', 'Rolling Valley', 'Franconia – Springfield [ Inactive ]', 'Landmark Mall [ Inactive ]', 'Van Dorn St [ Inactive ]'],
    peakHours: '4:15 PM – 5:30 PM',
    latitude: 38.896695,
    longitude: -77.043543,
    active: true,
    provenance: {
      state: 'needs-review',
      source: 'sluglines.com WordPress export (legacy site; its own content predates 2020)',
    },
  },
  {
    slug: '19th-st-and-i-st',
    routeSlug: '19th-St-and-I-St',
    name: '19th St and I St',
    corridor: 'I-395 / I-95',
    direction: 'Afternoon',
    county: 'Washington DC',
    destination: 'Northern Virginia commuter lots',
    description: 'Sluglines forms in front of the restaurant Heritage India (closed now) on 19th street between I street and Pennsylvania Avenue at 854 19th St NW, Washington, DC 20006 ( https://goo.gl/maps/BRsy77PixC62 ). Drivers heading south pull to their right and pick up slugs for Horner Road and Tackett’s. Slugging traffic to Potomac Mills slowed down after the Potomac Mills reduced the parking space for commuters in 2014.',
    linesFrom: ['Horner Rd', 'Potomac Mills', 'Telegraph Rd'],
    peakHours: '3:30 PM -5:00 PM',
    latitude: 38.900711,
    longitude: -77.043549,
    active: true,
    provenance: {
      state: 'needs-review',
      source: 'sluglines.com WordPress export (legacy site; its own content predates 2020)',
    },
  },
  {
    slug: 'lenfant-plaza',
    routeSlug: 'LEnfant-Plaza',
    name: 'L\'Enfant Plaza',
    corridor: 'I-395 / I-95',
    direction: 'Afternoon',
    county: 'Washington DC',
    destination: 'Fairfax, Prince William, and Stafford',
    description: 'Slug lines form along the sidewalk of D Street SW on both sides of the General Service Administration building entrance. Riders line up for Bobs and Rolling Valley between the 7th street and GSA building entrance. Riders for Horner road and 610 line up past the GSA entrance.',
    linesFrom: ['Bobs (Old Keene Mill Rd)', 'Rolling Valley', 'Horner Rd', 'Route 610 – Staffordboro Blvd', 'Route 610 – Mine Rd', 'Franconia – Springfield [ Inactive ]', 'Telegraph Rd', 'Landmark Mall [ Inactive ]', 'Van Dorn St [ Inactive ]', 'Vienna Metro South KnR', 'Fairfax Govt', 'Stringfellow PnR', 'Herndon-Monroe PnR', 'Cushing Road'],
    latitude: 38.88489,
    longitude: -77.023402,
    active: true,
    provenance: {
      state: 'needs-review',
      source: 'sluglines.com WordPress export (legacy site; its own content predates 2020)',
    },
    peakHours: '3:30 PM – 5:30 PM',
    fbUrl: 'https://www.facebook.com/groups/lenfantslugs/',
  },
  {
    slug: 'navy-yard',
    routeSlug: 'Navy-Yard',
    name: 'Navy Yard',
    corridor: 'I-395 / I-95',
    direction: 'Afternoon',
    county: 'Washington DC',
    destination: 'Northern Virginia commuter lots',
    description: 'The Washington Navy Yard is the oldest US Navy shore facility. Some of the sluggers use to slug into L’Enfant Plaza and take metro train to their destination. Morning lines are usually combined with L’Enfant lines. Early 2000 slugs started a yahoo group to coordinate afternoon rides. Directions from Virginia: Follow I-395 across the 14th St. Bridge. At the end of the Bridge, I-395 bears off to the right and becomes the Southwest-Southeast Freeway. Take the Freeway to the 6th St SE exit. Proceed down the ramp and continue straight ahead to 8th St SE. Turn right, go two blocks to M St SE. Turn left on M St SE and go three blocks to 11th St. Slugs line up at 300, M street SE Washington DC – 20003 . In 2015 Washington Navy Yard established couple more slug lines to Route 610 and Horner Road along the Patterson Ave.',
    linesTo: ['Horner Rd', 'Route 234', 'Route 610 – Mine Rd', 'Route 610 – Staffordboro Blvd'],
    linesFrom: ['Horner Rd', 'Telegraph Rd', 'Route 610 – Mine Rd [ Inactive ]', 'Vienna Metro South KnR [ Inactive ]', 'Stringfellow PnR [ Inactive ]'],
    peakHours: '4:00 PM – 5:30 PM',
    latitude: 38.8765811,
    longitude: -77.0014703,
    active: true,
    provenance: {
      state: 'needs-review',
      source: 'sluglines.com WordPress export (legacy site; its own content predates 2020)',
    },
  },
  {
    slug: 'state-department',
    routeSlug: 'state-department',
    name: 'State Department',
    corridor: 'I-395 / I-95',
    direction: 'Afternoon',
    county: 'Washington DC',
    destination: 'Horner Rd and Telegraph Rd',
    description: 'A proposed pickup point the legacy page describes as "a new pickup location ... still explored". Its own comment thread records that the line never formed.',
    latitude: null,
    longitude: null,
    active: false,
    provenance: {
      state: 'needs-review',
      source: 'sluglines.com WordPress export (legacy site; its own content predates 2020)',
    },
    linesFrom: ['Horner Rd', 'Telegraph Rd'],
    linesTo: ['Horner Rd', 'Telegraph Rd'],
    fbUrl: 'https://www.facebook.com/groups/dcsluglines/',
    notes: 'Legacy-only: present in the /slug_pickup/ inventory, absent from the curated live directory. Never operated. No coordinates on the legacy page.',
  },
  {
    slug: 'vienna-metro-south-knr',
    routeSlug: 'Vienna-Metro-South-KnR',
    name: 'Vienna Metro South KnR',
    corridor: 'I-66',
    direction: 'Morning',
    county: 'Fairfax',
    destination: 'Pentagon, Rosslyn, and L\'Enfant Plaza',
    description: 'Vienna Metro South KnR is a morning slug line location in Fairfax serving the I-66 corridor.',
    latitude: 38.8774069,
    longitude: -77.2706202,
    active: true,
    provenance: {
      state: 'needs-review',
      source: 'Directory addition for the I-66 corridor; no primary source recorded',
    },
    peakHours: '6:00 AM - 8:30 AM',
    fbUrl: 'https://www.facebook.com/groups/viennaslugs/',
  },
  {
    slug: 'fairfax-govt',
    routeSlug: 'Fairfax-Govt',
    name: 'Fairfax Govt',
    corridor: 'I-66',
    direction: 'Morning',
    county: 'Fairfax',
    destination: 'Pentagon, Rosslyn, and L\'Enfant Plaza',
    description: 'Fairfax Govt is a morning slug line location in Fairfax serving the I-66 corridor.',
    latitude: 38.8542902,
    longitude: -77.3604273,
    active: true,
    provenance: {
      state: 'needs-review',
      source: 'Directory addition for the I-66 corridor; no primary source recorded',
    },
    peakHours: '6:00 AM - 8:30 AM',
  },
  {
    slug: 'stringfellow-pnr',
    routeSlug: 'Stringfellow-PnR',
    name: 'Stringfellow PnR',
    corridor: 'I-66',
    direction: 'Morning',
    county: 'Fairfax',
    destination: 'Pentagon, Rosslyn, and L\'Enfant Plaza',
    description: 'Stringfellow PnR is a morning slug line location in Fairfax serving the I-66 corridor.',
    latitude: 38.854028,
    longitude: -77.404472,
    active: true,
    provenance: {
      state: 'needs-review',
      source: 'Directory addition for the I-66 corridor; no primary source recorded',
    },
    peakHours: '6:00 AM - 8:30 AM',
  },
  {
    slug: 'herndon-monroe-pnr',
    routeSlug: 'Herndon-Monroe-PnR',
    name: 'Herndon-Monroe PnR',
    corridor: 'I-66',
    direction: 'Morning',
    county: 'Fairfax',
    destination: 'Pentagon, Rosslyn, and L\'Enfant Plaza',
    description: 'Herndon-Monroe PnR is a morning slug line location in Fairfax serving the I-66 corridor.',
    latitude: 38.9513106,
    longitude: -77.3823065,
    active: true,
    provenance: {
      state: 'needs-review',
      source: 'Directory addition for the I-66 corridor; no primary source recorded',
    },
    peakHours: '6:00 AM - 8:30 AM',
  },
  {
    slug: 'cushing-road',
    routeSlug: 'Cushing-Road',
    name: 'Cushing Road',
    corridor: 'I-66',
    direction: 'Morning',
    county: 'Prince William',
    destination: 'Pentagon, Rosslyn, and L\'Enfant Plaza',
    description: 'Cushing Road is a morning slug line location in Prince William serving the I-66 corridor.',
    latitude: 38.7950597,
    longitude: -77.563859,
    active: true,
    provenance: {
      state: 'needs-review',
      source: 'Directory addition for the I-66 corridor; no primary source recorded',
    },
    peakHours: '5:45 AM - 8:00 AM',
  },
  {
    slug: 'east-gate',
    routeSlug: 'East-Gate',
    name: 'East Gate',
    corridor: 'I-66',
    direction: 'Morning',
    county: 'Loudoun',
    destination: 'Pentagon, Rosslyn, and L\'Enfant Plaza',
    description: 'East Gate is a morning slug line location in Loudoun serving the I-66 corridor.',
    latitude: 38.9119294,
    longitude: -77.4914467,
    active: true,
    provenance: {
      state: 'needs-review',
      source: 'Directory addition for the I-66 corridor; no primary source recorded',
    },
    peakHours: '5:45 AM - 8:00 AM',
  },
  {
    slug: 'stone-ridge',
    routeSlug: 'Stone-Ridge',
    name: 'Stone Ridge',
    corridor: 'I-66',
    direction: 'Morning',
    county: 'Loudoun',
    destination: 'Pentagon, Rosslyn, and L\'Enfant Plaza',
    description: 'Stone Ridge is a morning slug line location in Loudoun serving the I-66 corridor.',
    latitude: 38.938222,
    longitude: -77.555917,
    active: true,
    provenance: {
      state: 'needs-review',
      source: 'Directory addition for the I-66 corridor; no primary source recorded',
    },
    peakHours: '5:45 AM - 8:00 AM',
  },
  {
    slug: 'foggy-bottom',
    routeSlug: 'Foggy-Bottom',
    name: 'Foggy Bottom',
    corridor: 'I-66',
    direction: 'Afternoon',
    county: 'Washington DC',
    destination: 'Fairfax, Loudoun, and Prince William I-66 lines',
    description: 'Foggy Bottom is a afternoon slug line location in Washington DC serving the I-66 corridor.',
    latitude: 38.90075,
    longitude: -77.049611,
    active: true,
    provenance: {
      state: 'needs-review',
      source: 'Directory addition for the I-66 corridor; no primary source recorded',
    },
    peakHours: '3:30 PM - 6:30 PM',
  },
]

/** Asserted against the seeded row count by the migration and by its test. */
export const SPOT_LOCATION_COUNT = SPOT_LOCATIONS.length

const BY_SLUG: ReadonlyMap<string, SpotLocation> = new Map(
  SPOT_LOCATIONS.map((location) => [location.slug, location])
)

/**
 * Slugs are compared case-insensitively everywhere. The legacy site used
 * lower-case URLs and this app serves mixed case, so a caller may hold either.
 */
export function canonicalSlug(slug: string) {
  return slug.trim().toLowerCase()
}

export function findSpotLocation(slug: string): SpotLocation | undefined {
  return BY_SLUG.get(canonicalSlug(slug))
}

export function hasSpotLocation(slug: string) {
  return BY_SLUG.has(canonicalSlug(slug))
}

export function activeSpotLocations() {
  return SPOT_LOCATIONS.filter((location) => location.active)
}

export function inactiveSpotLocations() {
  return SPOT_LOCATIONS.filter((location) => !location.active)
}

export function spotLocationsByCorridor(corridor: SpotCorridor) {
  return SPOT_LOCATIONS.filter((location) => location.corridor === corridor)
}

export function spotLocationsByDirection(direction: SpotDirection) {
  return SPOT_LOCATIONS.filter((location) => location.direction === direction)
}

export function spotLocationCounties(locations: readonly SpotLocation[] = SPOT_LOCATIONS) {
  return Array.from(new Set(locations.map((location) => location.county)))
}

export interface SpotLocationCorridorGroup {
  corridor: SpotCorridor
  directions: {
    direction: SpotDirection
    counties: { county: string; locations: SpotLocation[] }[]
  }[]
}

/**
 * Corridor → direction → county, with empty groups dropped. Directions are
 * emitted in `SPOT_DIRECTIONS` order (Morning before Afternoon) rather than in
 * first-seen order, because that is a commute-day ordering and not a data one.
 */
export function groupSpotLocations(
  locations: readonly SpotLocation[] = SPOT_LOCATIONS
): SpotLocationCorridorGroup[] {
  const corridors = SPOT_CORRIDORS.filter((corridor) =>
    locations.some((location) => location.corridor === corridor)
  )

  return corridors.map((corridor) => ({
    corridor,
    directions: SPOT_DIRECTIONS.map((direction) => {
      const inDirection = locations.filter(
        (location) => location.corridor === corridor && location.direction === direction
      )

      return {
        direction,
        counties: spotLocationCounties(inDirection).map((county) => ({
          county,
          locations: inDirection.filter((location) => location.county === county),
        })),
      }
    }).filter((group) => group.counties.length > 0),
  }))
}

export interface SpotCoordinates {
  latitude: number
  longitude: number
}

const EARTH_RADIUS_MILES = 3958.8

function toRadians(value: number) {
  return (value * Math.PI) / 180
}

export function distanceInMiles(from: SpotCoordinates, to: SpotCoordinates) {
  const latitudeDistance = toRadians(to.latitude - from.latitude)
  const longitudeDistance = toRadians(to.longitude - from.longitude)

  const haversine =
    Math.sin(latitudeDistance / 2) ** 2 +
    Math.cos(toRadians(from.latitude)) *
      Math.cos(toRadians(to.latitude)) *
      Math.sin(longitudeDistance / 2) ** 2

  return EARTH_RADIUS_MILES * 2 * Math.atan2(Math.sqrt(haversine), Math.sqrt(1 - haversine))
}

/**
 * Distance from `origin`, or `Infinity` for a spot with no surveyed coordinate.
 * `Infinity` rather than `null` so it sorts last without a special case at every
 * call site — an uncoordinated spot is never the nearest one.
 */
export function spotLocationDistance(location: SpotLocation, origin: SpotCoordinates) {
  if (location.latitude === null || location.longitude === null) {
    return Number.POSITIVE_INFINITY
  }

  return distanceInMiles(origin, { latitude: location.latitude, longitude: location.longitude })
}

export function nearestSpotLocations(
  origin: SpotCoordinates,
  options: { limit?: number; locations?: readonly SpotLocation[] } = {}
) {
  const { limit, locations = SPOT_LOCATIONS } = options

  const ranked = locations
    .map((location) => ({ location, miles: spotLocationDistance(location, origin) }))
    .filter((entry) => Number.isFinite(entry.miles))
    .sort((left, right) => left.miles - right.miles)

  return typeof limit === 'number' ? ranked.slice(0, limit) : ranked
}
