-- =============================================================================
-- 0009_spot_content_refresh.sql
--
-- APPLIED: no
-- TARGET:  not yet applied. Applying it is a separate, separately authorised act
--          -- see supabase/migrations/README.md.
--
-- GENERATED FILE -- DO NOT EDIT BY HAND.
--   Source:    src/lib/domain/locations.ts
--   Generator: scripts/seed-locations.mjs   (`npm run seed:locations`)
--   Guard:     tests/spot-locations-directory.test.mjs re-runs the generator and
--              compares the result with this file byte-for-byte.
--
-- WHY THIS EXISTS RATHER THAN A REGENERATED 0004
-- -----------------------------------------------------------------------------
-- 0004 seeded these columns and is APPLIED: production. The directory it was
-- generated from has since been rewritten from the legacy sluglines.com pages,
-- which carried materially more per-spot detail than the paraphrases this repo
-- shipped with -- parking broken down by lot and space count, peak-hour windows,
-- and the actual named lines each spot runs to and from. Editing 0004 to match
-- would falsify a record of what production ran. So the facts move forward in a
-- new ordinal and 0004 stays exactly as it was applied. Docs/DECISIONS.md D-59.
--
-- SCOPE
-- -----------------------------------------------------------------------------
-- Five columns, all of them operational facts. Identity (slug, route_slug,
-- name), geography (latitude, longitude, county, corridor, direction),
-- is_active, community_url and notes are untouched: this migration answers "what
-- does this spot's page say", not "which spot is this".
-- =============================================================================

update public.locations as l set
  description = seed.description,
  peak_hours = seed.peak_hours,
  parking = seed.parking,
  lines_from = seed.lines_from,
  lines_to = seed.lines_to
from (
  values
      ('bobs-old-keene-mill-rd', 'There are 2 slug staging areas at Bobs, primarily going to DC locations at the Keene Mill Park and Ride behind the gas station next to the bus shelter goes to 18th, 20th and 23rd street. The line away from the gas station goes to 14th street and L’Enfant. Bob’s pickup location is closed for construction. For more details check https://sluglines.com/blog/bobs-slug-line-and-parking-relocation-plan/. 14th Street / L’Enfant Plaza lines will be relocated to the Springfield Town Center Garage, join https://www.facebook.com/groups/stcsluglines to coordinate. 18th Street line will be relocated to the Springfield United Methodist Church, 7047 Old Keene Mill Rd, Springfield, VA 22150.', '5:45 AM – 8:00 AM', 'There are about 685 parking spaces, it gets full by 7:00 AM. At the shopping complex and American Legion, commuter parking spaces are marked in blue. 254 spaces Springfield plaza, 7206 Old Keene Mill Rd, Springfield, VA 22150 ( http://www.myspringfieldplaza.com ). 100 spaces American Legion, 6500 Amherst Avenue, Springfield, VA 22150. 53 spaces 7047 Old Keene Mill Rd, Springfield, VA 22150 ( http://www.sumc-cares.org ). 278 spaces former Circuit City lot, 7039 Old Keene Mill Road, Springfield, VA 22150.', array['L’Enfant Plaza', '14th at Commerce Dept.', '18th Street']::text[], array['L’Enfant Plaza', '14th at Commerce Dept.', '14th & Madison Dr', '19th & F Street']::text[]),
      ('cardinal-forest-plaza', 'Cardinal Forest aka Rolling Road sluglines form next to the Shell station (https://goo.gl/maps/apZGwkefh6x) on Old Keene Mill Road across the Cardinal Forest Shopping complex. Slugs park their vehicle in front of the shopping complex and cross the road to lineup near the bus stop for Pentagon.', '6:30 AM – 8:00 AM', '100 Spaces near TD Bank (https://goo.gl/maps/KegSdkmzXi92).', array['The Pentagon']::text[], array['14th Street and Constitution Ave', 'L’Enfant Plaza', 'The Pentagon', '19th & F St', '15th Street & New York Ave']::text[]),
      ('franconia-springfield', 'Franconia-Springfield is a major transit hub, with both rail and bus service. WMATA metro rail services operate all day and Virginia Railway Express operates during peak hours. There are several bus services operated by WMATA, Fairfax connector, PRTC, and Greyhound.', '07:00 AM – 08:00 AM', '5,069 spaces.', null::text[], null::text[]),
      ('lorton', 'Riders line up in front of the VRE station at the parking lot. Most of the riders go to Pentagon and take a metro from there to their work location. There is a designated staging area for Lorton slugs at the Pentagon parking lot.', '3:00 PM – 6:00 PM', '567 Spaces VRE Lorton.', array['The Pentagon']::text[], array['The Pentagon']::text[]),
      ('rolling-valley', 'Rolling Valley is one of the biggest lot in Fairfax County with 664 parking spaces. This location is famous for slugging to the Pentagon and L’Enfant Plaza other destinations have lesser traffic.', '7:00 AM – 8:00 AM', '664 spaces.', array['The Pentagon', 'Rosslyn', 'Crystal City', 'L’Enfant Plaza', '14th Street', '18th / 20th / 23rd Street up to Pennsylvania Ave']::text[], array['The Pentagon', 'Rosslyn', 'L’Enfant Plaza', '14th Street and Constitution Ave', '19th & F St']::text[]),
      ('saratoga', 'Saratoga parking lot is right off the new section of the Fairfax County Parkway, provides an easy access to I-95. Slugs use this line along with Sydenstricker’s Rd and Rolling Valley as all the SlugStops destined to go to Pentagon.', '6:00 AM – 8:00 AM', '535 parking spaces.', array['The Pentagon']::text[], array['The Pentagon']::text[]),
      ('sydenstricker-rd', 'The Sydenstricker primarily servers Pentagon drivers and riders, some drivers call for Crystal City or Rosslyn. All riders share the one line for all stops. Riders line up along the concrete sidewalk at the parking lot.', '5:45 A.M – 8:00 A.M', '170 Spaces Sydenstricker Road 8500 Hooes Road, Springfield, VA 22153.', array['The Pentagon', 'Rosslyn']::text[], array['The Pentagon', 'L’Enfant Plaza', '14th Street and Constitution Ave']::text[]),
      ('springfield-town-center', 'There are about 500 parking spaces leased by Fairfax County for commuters. County is leasing additional 300 spaces to accommodate Bobs slugs. There are no sluglines at this time, but commuters park at this garage and walk to the Franconia-Springfield Metro station, primarily because parking is free at this location. With the Clean Fuel tags that expired last month and the new I-395 Express Lanes that are opening on November 17th, 2019 this will be an option for commuters from East of I-95.', null::text, '800 spaces.', array['L’Enfant Plaza', '14th at Commerce Dept.', '18th Street']::text[], array['L’Enfant Plaza', '14th at Commerce Dept.', '14th & Madison Dr', '19th & F Street']::text[]),
      ('van-dorn-st', 'Van Dorn Metro park-and-ride. The legacy page title carries an explicit [Inactive] marker.', '07:00 AM – 08:00 AM', '361 spaces.', array['L''Enfant Plaza', '14th Street', '18th Street']::text[], array['L''Enfant Plaza', '14th & Madison Ave', '19th & F Street']::text[]),
      ('landmark-mall', 'Bus stop #4000576 on the Landmark Mall roadway. The legacy page title carries an explicit [Inactive] marker.', '07:00 AM – 08:00 AM', 'Parking available next to bus stop #4000576 (Landmark Mall Rdwy & Mall Entrance) on the lower level of the parking garage in rows K, L, M, N, and O. Parking permits are required and can be obtained by emailing goalex@alexandriava.gov. Parking is limited and available on a first-come, first-serve basis.', array['L''Enfant Plaza', '14th Street', '18th Street']::text[], null::text[]),
      ('route-3-gordon-rd', 'The Gordon road commuter lot is located at the intersection of Route 3 and Gordon road in Spotsylvania County. It is approximately 3 miles west of I-95 (exit 130). There are few commuters going to Quantico, Tysons and Alexandria, having a sign will help get a direct ride to your destination. Consider joining Rt. 3 Facebook Group to coordinate rides.', '5:30 AM – 6:30 AM', '1,052 parking spaces.', array['The Pentagon', 'Rosslyn [ Inactive ]', 'Quantico [ Inactive ]', 'Crystal City [ Inactive ]']::text[], array['The Pentagon', 'Rosslyn']::text[]),
      ('route-17', 'The Rt. 17 lot is an early lot, commuters leave the lot before 7 AM. Commuters can get to Pentagon, L’Enfant or 14th street. Drivers and riders are encouraged to display signs for their destinations such as Rosslyn and Crystal City.', '5:30 A.M – 8:30 A.M', 'The new lot will have a total of 1,865 parking spaces.', array['L’Enfant Plaza', '14th St at Commerce Dept.', 'The Pentagon', 'Rosslyn', 'Crystal City 23rd Street']::text[], array['The Pentagon', 'Rosslyn', 'Crystal City 23rd Street']::text[]),
      ('route-208', 'Take I-95 to Exit 126A. The morning slugs depart Fredericksburg from Route 208 SlugStop, and terminates at the Pentagon in about 1 hour and 25 minutes. Business Route 208 is heavily impacted by traffic as it becomes a route to several Spotsylvania county’s department. So sluggers need to be alert on traffic signs of incoming drivers.', '5:00 A.M – 6:30 A.M', '805 Free Parking Spaces in Spotsylvania County, located on Houser Drive Off Route 208.', array['14th St at Commerce Dept.', 'Crystal City 23rd Street', 'The Pentagon', 'Rosslyn']::text[], null::text[]),
      ('dale-city', 'The Dale City Park and Ride is located at the intersection of Dale Blvd. and Gemini Way in Dale City, VA hidden behind Gaint Food. The lot is along the Gemini Way accessible from Dale Blvd. or Minnieville Road. Slugs from one line for both Pentagon and Rosslyn and the lot always has space for parking. Slugging picked up from this lot after Potomac Mills reduced commuter parking space, but as there is no return lines from Pentagon most of the slugs get a ride to Horner or Potamac Mills and take a bus from there to Dale City parking lot.', '6:30 AM – 7:30 AM', '591 Spaces.', array['Crystal City', 'Rosslyn', 'The Pentagon']::text[], null::text[]),
      ('horner-rd', 'The Horner Road Commuter Parking Lot is situated to west of I-95 and north of Prince William Parkway, a free parking lot, maintained by VDoT. It is one of the largest parking lots in Prince William County having about 3100 parking spaces, but still fills up by about 7.30 AM. This is a very popular lot for slugging and has a ride back for almost all destinations. Due to its popularity and demand, VDoT and Prince William County added another 600 parking spaces in 2015. This lot has direct access to the I-95 HOT lanes.', '5:30 A.M – 7:00 A.M', '2363 spaces in the old lot on the east of Telegraph Road. 600 spaces in the new lot on west of Telegraph Road.', array['14th Street', '18th Street', 'Crystal City', 'L’Enfant Plaza and Navy Yard', 'Mark Center', 'Rosslyn', 'The Pentagon']::text[], array['L’Enfant Plaza', 'Navy Yard', '14th St at Commerce Dept.', '15th Street & New York Ave', '19th & I Street', 'The Pentagon', 'Mark Center', 'Rosslyn', 'Crystal City 12th Street', 'Crystal City 23rd Street']::text[]),
      ('montclair-fire-station', 'Montclair Fire Station is also know as Montclair / Dumfries parking lot. Parking is Limited along Spring branch Boulevard. To avoid heavier traffic in water way drive proceeding north along Spring branch boulevard.', '6:00 AM – 6:30 AM', '52 Spaces.', array['The Pentagon']::text[], array['The Pentagon']::text[]),
      ('montclair-northgate', 'Parking is along the north-gate and eastern side of waterway drive. An alternative route has been planned for growing ridership to Downtown D.C area for the buses that stop at pentagon. Once it is completed the Montclair community will have two routes separately for Downtown Washington and pentagon. It provides an effective alternative mode for sluggers as this changing bus routes provides morning and evening buses.', '5:30 A.M – 6:30 A.M', '52 Spaces.', array['The Pentagon']::text[], array['15th Street & New York Ave', 'The Pentagon']::text[]),
      ('old-hechingers', 'The parking has a parking capacity of 580 spaces with three entry/exit points from Old Bridge Road, Route 123 and Devils Reach Road. Riders line up at the bus stop in the parking lot and drivers pull up in the bus lane to pick up riders. Old Hechinger Commuter lot was named after the old home improvement chain store Hechinger Company that was closed in 1999. The store at this location was demolished to add about 250 parking spaces to the existing 400 spaces.', '7:00 -8:00 A.M', '580 spaces,. 1310 Old Bridge Road,. Woodbridge, VA 22192.', array['14th St at Commerce Dept. and 18th Street']::text[], array['Pentagon', '14th Street and Constitution Ave', '15th Street & New York Ave']::text[]),
      ('potomac-mills', 'Potomac Mills mall parking has been reduced from 1000 spaces to 275 to reduce the congestion at customer parking at the Potomac Mills Mall. With limited parking space, not many people slug from this lot.', '6:30 AM – 8:15 AM', '275 Parking Spaces around Potomac Mills Circle, commuters are allowed to park only in the parking spots that are marked in yellow.', array['18th Street']::text[], array['The Pentagon', '15th Street & New York Ave', 'Rosslyn']::text[]),
      ('route-123', 'Slug line from Route 123 is not an established line, drivers going to Tysons swing to pickup bus riders going to Tysons. There is no return lines from Tysons to Route 123. The lot is easily accessible from Gordon Blvd and exit 160 of I-95.', 'Peak rides: 6:20 AM – 8:15 AM', '770 Spaces along the intersection of Route 123 & I-95.', array['The Pentagon', 'Tysons Corner']::text[], null::text[]),
      ('route-234', 'The Parking lot has its easy access to US 1 express highway lanes (Jefferson Davis Highway)and Exit 152 So it is highly competitive for drivers to find parking as the commuters come from Dumfries, Triangle, Stafford, and even Fredericksburg.', '6:00 AM – 7:00 AM', 'The increase in capacity by 400 spaces makes total of 830 Parking Spaces along US 1 (Jefferson Davis Highway) at Route 234 (Dumfries Road).', array['14th Street and L’Enfant Plaza', 'Crystal City', 'Rosslyn', 'The Pentagon', '18th Street']::text[], null::text[]),
      ('tacketts-mill', 'The Tackett’s Mill Commuter lot is at the intersection of Minnieville Road and Old Bridge Road. Riders lineup in two locations, one going to the Pentagon and other goes to Rosslyn and Crystal City. There is also a overflow parking lot across this lot in the shopping complex, but make sure to park only in the commuter parking spaces.', '7:00 AM – 8:30 AM', 'Tackett’s Mill Commuter lot has about 530 Spaces. Overflow parking is across the lot in the shopping complex or called McDonald’s lot with 120 spaces.', array['Crystal City and Rosslyn', 'The Pentagon']::text[], array['The Pentagon', 'Crystal City', 'Rosslyn']::text[]),
      ('telegraph-rd', 'The Telegraph Rd. Commuter Lot is on the Telegraph Road, next to the Sheets Gas Station. Lot can be accessed both from the Caton Hill Road and Telegraph Road. Slugging provides a great opportunity for growing ridership, as there is lack of commuter parking in Horner Road Commuter Lot.', '7:00 AM – 8:15 AM', '600 Free parking Spaces.', array['14th Street', '18th Street', 'Crystal City', 'L’Enfant Plaza and Navy Yard', 'Rosslyn', 'The Pentagon', 'Mark Center']::text[], array['L’Enfant Plaza', '14th St at Commerce Dept.', '15th Street & New York Ave', '19th & I St', 'Crystal City 23rd St', 'Crystal City 12th St', 'Navy Yard', 'The Pentagon', 'Rosslyn', 'Mark Center']::text[]),
      ('route-610-mine-rd', 'The Mine Road lot with 750 parking spaces is on the south of Rt. 610 Garrisonville Road. This parking lot fills up early, alternate parking space is on the Staffordboro Blvd. not or Rt. 610. There are two lines one going to Arlington and the other to DC destinations.', '5:30 AM – 6:30 AM (Slugs line up as early as 4:30 AM)', '750 spaces. Alternate parking at Staffordboro Parking Lot.', array['L’Enfant Plaza', 'Navy Yard', '14th & G Street', '18th Street', 'The Pentagon', 'Crystal City']::text[], array['L’Enfant Plaza', 'The Pentagon', 'Rosslyn', 'Crystal City', '14th and G Street', '14th and Independence Ave (New)', 'Public Transportation', 'FRED Routes D4 and D6']::text[]),
      ('route-610-staffordboro-blvd', 'The Staffordboro Blvd Park & Ride lot in Garrisonville was opened on October 2014, with 1,865 parking spaces. This is one of the few lots that has Slug pickup areas, that can accommodate about 30 people to line up and 4 ideal cars. Riders going to the Pentagon, Rosslyn, Crystal City and DC locations form a single line. Commuters also discuss commuting challenges in the Facebook Group https://www.facebook.com/groups/StaffordSluglines/.', '5:00 AM – 7:30 AM', '1,865 parking spaces.', array['The Pentagon', 'Rosslyn', 'Crystal CIty', 'L’Enfant Plaza']::text[], array['The Pentagon', 'Rosslyn', 'Crystal City 12th and 23rd', 'L’Enfant Plaza', '14th and G Street', '14th and Independence Ave']::text[]),
      ('route-630', 'Sluglines is located near the bus shelter. The traffic is eased by the VDOT reconstruction of lanes at the intersection between Route 630 (Courthouse Road) and I-95 Interchange.', '5:30 AM – 6:30 AM', 'The 539 reduced space parking facility is located off Route 630 just west of I-95.', array['The Pentagon', 'Rosslyn', 'Crystal City']::text[], array['The Pentagon']::text[]),
      ('mark-center', 'The Mark Center is a federal building opened in 2012 for DoD agencies. The Mark Center provides a designated staging area for slugging at the entrance of North Parking Garage on Mark Center Drive. Currently slugging is mostly coordinated by three different mailing lists to different locations. Mailing list is not open to public, commuters have to be a DoD personnel to access enroll to this mailing list others join the Mark Center Sluglines Facebook Group. Horner/Tacketts Mills: whs.mc-alex.hrd.list.sluggers-horner-tacketts@mail.mil. Route 234: whs.mc-alex.hrd.list.sluggers-montclair-234@mail.mil. Stafford/Fredericksburg: whs.mc-alex.hrd.list.sluggers-stafford-fredericksburg@mail.mil. There are no morning slug lines going to the Mark Center, commuters line up with the Pentagon lines and circle back to the Mark Center via Metrobus (Free for commuters with CAC). Some commuters coordinate rides.', '4:00 PM – 5:00 PM', null::text, array['Horner Rd', 'Route 234', 'Tacketts Mill [ Inactive ]', 'Telegraph Rd', 'Route 610 – Staffordboro Blvd']::text[], null::text[]),
      ('tysons-corner', 'Tysons Corner slug pickup is located at the bus stop on Jones Branch Dr. between Lincoln Way & Lincoln Center Ct. ahead of Fountains at McLean, 1503 Lincoln Center Ct. McLean, VA 22102.', '3:30 PM - 6:30 PM', null::text, array['Route 123']::text[], null::text[]),
      ('crystal-city-12th-st', 'The line forms at the northern end of Crystal City near the sharp turn on Crystal Drive and 12th Street 1272 Crystal Dr, Arlington, VA 22202 ( https://goo.gl/maps/SVHcnBKvozM2 ). Drivers heading north on Crystal Drive pick up slugs for Woodbridge Lines ( Horner Road and Tacketts Mill) near the bus stop and Stafford Lines (Route 610) in front of the park sign.', '4:00 PM – 5:00 PM', null::text, array['Route 610 (Stafford)', 'Horner Rd', 'Tacketts Mill', 'Telegraph Rd']::text[], null::text[]),
      ('crystal-city-23rd-st', 'Sluglines form along the Crystal Drive near the Bright Horizons day care at 2451 Crystal Dr, Arlington, VA 22202 ( https://goo.gl/maps/pce3ibvok462 ). Drivers heading north on Crystal Drive pick up slugs for Horner Road and Tacketts Mill just before the cross walk light and Route 610 slugs past this cross walk.', '4:00 PM – 5:00 PM', null::text, array['Route 610 (Stafford)', 'Horner Rd', 'Tacketts Mill', 'Telegraph Rd']::text[], null::text[]),
      ('rosslyn', 'In 2002, Arlington county placed signs for sluglines staging area at this location for Springfield, Woodbridge and Frediricksburg Commuters. Sluglines to Bobs / Springfield forms in the corner for N.Kent Street and Wilson Blvd. Riders line up on the N. Kent Street, the nearest address is 1601, North Kent Street, Arlington, VA – 22209. Sluglines to Tacketts, Horner, Potomac and Stafford forms between North Moore Street and North Fort Myer Drive on the Lee Highway service road.', '3:15 PM – 6:00 PM', null::text, array['North Kent Street', 'Bobs (Old Keene Mill Rd)', 'Rolling Valley', 'Lee Highway service road', 'Horner Rd', 'Potomac Mills [ Inactive ]', 'Old Hechingers [ Inactive ]', 'Stafford']::text[], null::text[]),
      ('the-pentagon', 'Sluglines was started in the mid 1970’s between the Pentagon and the Bob’s at Springfield. Since then it had been growing and today we have about 5000 commuters slug from the Pentagon to different locations along I-95 corridor. The I-66 tolls inside beltway that started on December 4, 2017, drivers are looking to pick up riders from the Pentagon. The new off ramp from the north bound I-395 Express Lanes to the Pentagon South Parking lot that was opened on November 17th 2019 has significantly reduced the morning backups on the old HOV-3 lanes.', '3:00 PM – 6:00 PM', null::text, null::text[], null::text[]),
      ('14th-st-and-constitution-ave', 'The 14th and Constitution slug pick up location that serves Springfield commuters has been moved to 14th and Madison. Riders heading to Bob’s and Rolling Valley line up here in single file at this location. The driver has to call out their drop off location, to pickup riders. It is challenging for drivers to pull up and pick up riders when food trucks parked taking the right lane. Drivers, when you are stopping on the second left lane to pick up riders, it is not safe and traffic officers may ticket you.', '3:30 PM – 6:00 PM', null::text, array['Bobs – Old Keene Mill Rd', 'Rolling Valley']::text[], null::text[]),
      ('14th-st-and-g-st', '14th St and G St is a afternoon slug line location in Washington DC serving the I-395 / I-95 corridor.', '3:30 PM – 5:00 PM', null::text, array['Route 610']::text[], null::text[]),
      ('14th-st-and-independence', 'Due to excess congestion of this slugline between parking buses and slugging cars, carpooling has been shifted to new area. The slugline is relocated to north of intersection near the railing on auditors building. The sluggers can access both bus and car at this stop.', '3:00 PM – 5:30 PM', null::text, array['Potomac Mills', 'Horner Rd', 'Route 234', 'Telegraph Rd', 'Old Hechingers']::text[], null::text[]),
      ('14th-st-at-commerce-dept', 'The sluglines are co-located with the bus stop on the 14th Street in front of the Commerce building, between Pennsylvania Ave NW and Constitution Ave NW. Due to the construction slugs move between between Pennsylvania Ave NW and Constitution Ave NW.', '4:00 PM – 5:00 PM', null::text, array['Horner Rd', 'Potomac Mills', 'Old Hechingers', 'Telegraph Rd', 'Tacketts Mill']::text[], null::text[]),
      ('15th-st-and-new-york-ave', 'Riders line up along NY Ave NW near the 15th St. Cars have enough space to pull up and wait as the street side parking is not allowed after 3.00 PM. It is convenient riders to hope on the PRTC bus stops.', '3:00 P.M – 6:00 P.M', null::text, array['Horner Rd', 'Potomac Mills', 'Old Hechingers', 'Tacketts Mill', 'Telegraph Rd', 'Vienna Metro South KnR', 'Fairfax Govt', 'Stringfellow PnR', 'Herndon-Monroe PnR', 'Cushing Road']::text[], null::text[]),
      ('19th-st-and-f-st', 'Line forms on 19th street between F and E street in front of The George Washington University – Mitchell Hall entrance. This is one of the old and popular lines that was moved from 18th and F street to 19th and F.', '4:15 PM – 5:30 PM', null::text, array['Bobs (Old Keene Mill Rd)', 'Rolling Valley', 'Franconia – Springfield [ Inactive ]', 'Landmark Mall [ Inactive ]', 'Van Dorn St [ Inactive ]']::text[], null::text[]),
      ('19th-st-and-i-st', 'Sluglines forms in front of the restaurant Heritage India (closed now) on 19th street between I street and Pennsylvania Avenue at 854 19th St NW, Washington, DC 20006 ( https://goo.gl/maps/BRsy77PixC62 ). Drivers heading south pull to their right and pick up slugs for Horner Road and Tackett’s. Slugging traffic to Potomac Mills slowed down after the Potomac Mills reduced the parking space for commuters in 2014.', '3:30 PM -5:00 PM', null::text, array['Horner Rd', 'Potomac Mills', 'Telegraph Rd']::text[], null::text[]),
      ('lenfant-plaza', 'Slug lines form along the sidewalk of D Street SW on both sides of the General Service Administration building entrance. Riders line up for Bobs and Rolling Valley between the 7th street and GSA building entrance. Riders for Horner road and 610 line up past the GSA entrance.', '3:30 PM – 5:30 PM', null::text, array['Bobs (Old Keene Mill Rd)', 'Rolling Valley', 'Horner Rd', 'Route 610 – Staffordboro Blvd', 'Route 610 – Mine Rd', 'Franconia – Springfield [ Inactive ]', 'Telegraph Rd', 'Landmark Mall [ Inactive ]', 'Van Dorn St [ Inactive ]', 'Vienna Metro South KnR', 'Fairfax Govt', 'Stringfellow PnR', 'Herndon-Monroe PnR', 'Cushing Road']::text[], null::text[]),
      ('navy-yard', 'The Washington Navy Yard is the oldest US Navy shore facility. Some of the sluggers use to slug into L’Enfant Plaza and take metro train to their destination. Morning lines are usually combined with L’Enfant lines. Early 2000 slugs started a yahoo group to coordinate afternoon rides. Directions from Virginia: Follow I-395 across the 14th St. Bridge. At the end of the Bridge, I-395 bears off to the right and becomes the Southwest-Southeast Freeway. Take the Freeway to the 6th St SE exit. Proceed down the ramp and continue straight ahead to 8th St SE. Turn right, go two blocks to M St SE. Turn left on M St SE and go three blocks to 11th St. Slugs line up at 300, M street SE Washington DC – 20003 . In 2015 Washington Navy Yard established couple more slug lines to Route 610 and Horner Road along the Patterson Ave.', '4:00 PM – 5:30 PM', null::text, array['Horner Rd', 'Telegraph Rd', 'Route 610 – Mine Rd [ Inactive ]', 'Vienna Metro South KnR [ Inactive ]', 'Stringfellow PnR [ Inactive ]']::text[], array['Horner Rd', 'Route 234', 'Route 610 – Mine Rd', 'Route 610 – Staffordboro Blvd']::text[]),
      ('state-department', 'A proposed pickup point the legacy page describes as "a new pickup location ... still explored". Its own comment thread records that the line never formed.', null::text, null::text, array['Horner Rd', 'Telegraph Rd']::text[], array['Horner Rd', 'Telegraph Rd']::text[]),
      ('vienna-metro-south-knr', 'Vienna Metro South KnR is a morning slug line location in Fairfax serving the I-66 corridor.', '6:00 AM - 8:30 AM', null::text, null::text[], null::text[]),
      ('fairfax-govt', 'Fairfax Govt is a morning slug line location in Fairfax serving the I-66 corridor.', '6:00 AM - 8:30 AM', null::text, null::text[], null::text[]),
      ('stringfellow-pnr', 'Stringfellow PnR is a morning slug line location in Fairfax serving the I-66 corridor.', '6:00 AM - 8:30 AM', null::text, null::text[], null::text[]),
      ('herndon-monroe-pnr', 'Herndon-Monroe PnR is a morning slug line location in Fairfax serving the I-66 corridor.', '6:00 AM - 8:30 AM', null::text, null::text[], null::text[]),
      ('cushing-road', 'Cushing Road is a morning slug line location in Prince William serving the I-66 corridor.', '5:45 AM - 8:00 AM', null::text, null::text[], null::text[]),
      ('east-gate', 'East Gate is a morning slug line location in Loudoun serving the I-66 corridor.', '5:45 AM - 8:00 AM', null::text, null::text[], null::text[]),
      ('stone-ridge', 'Stone Ridge is a morning slug line location in Loudoun serving the I-66 corridor.', '5:45 AM - 8:00 AM', null::text, null::text[], null::text[]),
      ('foggy-bottom', 'Foggy Bottom is a afternoon slug line location in Washington DC serving the I-66 corridor.', '3:30 PM - 6:30 PM', null::text, null::text[], null::text[])
) as seed(slug, description, peak_hours, parking, lines_from, lines_to)
where l.slug = seed.slug;
